@extends('layouts.app')
@section('title','Dashboard SIGET')
@section('page-title', $presentation['title'] ?? 'Dashboard SIGET')
@section('page-subtitle', $presentation['subtitle'] ?? 'Información de SIGET')
@section('content')
@php
$role = auth()->user()?->role?->code;
$k = $analytics['kpis'] ?? [];
$filters = $filters ?? [];
$monthly = collect($analytics['monthly_trend'] ?? []);
$units = collect($analytics['unit_performance'] ?? $analytics['direction_performance'] ?? []);
$agencies = collect($analytics['agency_performance'] ?? []);
$status = $analytics['status_distribution'] ?? [];
$total = max((int)($k['total'] ?? 0), 1);
$closed = (int)($k['closed'] ?? 0);
$overdue = (int)($k['overdue'] ?? 0);
$active = (int)($k['active'] ?? 0);
$reprogrammed = (int)($k['reprogrammed'] ?? 0);
$completion = (float)($k['completion_average'] ?? 0);
$compliance = (float)($k['compliance'] ?? 0);
$closureRate = round(($closed / $total) * 100, 1);
$riskRate = round(($overdue / $total) * 100, 1);
$activeRate = round(($active / $total) * 100, 1);
$reprogramRate = round(($reprogrammed / $total) * 100, 1);
@endphp

@if($role === 'DIRECTOR_GENERAL')
<section class="siget-hero mb-4"><div class="d-flex justify-content-between align-items-start gap-3"><div><span class="badge text-bg-primary mb-2">Vista ejecutiva institucional</span><h2>Centro Ejecutivo Institucional</h2><p>Situación global, desempeño comparativo, riesgo y tendencia. Esta vista no muestra bandejas ni rutas operativas.</p></div><div class="text-end"><small class="d-block text-muted">Universo analizado</small><strong class="fs-5">{{ number_format($k['total'] ?? 0) }} cargas</strong></div></div></section>
@include('dashboard.partials.filters')
<div class="row g-3 mb-4">
@foreach([['Cumplimiento institucional',$compliance,'%','bi-check2-circle','success'],['Avance medio',$completion,'%','bi-speedometer2','primary'],['Cierre efectivo',$closureRate,'%','bi-patch-check','info'],['Presión de riesgo',$riskRate,'%','bi-exclamation-triangle','danger'],['Estabilidad operativa',100-$reprogramRate,'%','bi-graph-up-arrow','success'],['Cargas activas',$active,'','bi-activity','secondary']] as $card)<div class="col-6 col-xl-2"><div class="siget-kpi h-100"><div class="siget-kpi-icon text-bg-{{ $card[4] }}"><i class="bi {{ $card[3] }}"></i></div><div><small>{{ $card[0] }}</small><strong>{{ $card[1] }}{{ $card[2] }}</strong></div></div></div>@endforeach
</div>
<div class="row g-4"><div class="col-xl-8"><div class="card siget-card h-100"><div class="card-header"><h2>Tendencia institucional</h2><p>Evolución del volumen de trabajo frente a los cierres.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><h2>Composición institucional</h2><p>Cómo se distribuye el universo actual.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleStatusChart"></canvas></div></div></div></div><div class="col-xl-7"><div class="card siget-card h-100"><div class="card-header"><h2>Desempeño comparativo por Dirección</h2><p>La Dirección General ve brechas, no registros individuales.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleDirectionChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card siget-card h-100"><div class="card-header"><h2>Concentración de riesgo por Dependencia</h2><p>Identifica dónde se concentra la presión institucional.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleAgencyChart"></canvas></div></div></div></div></div>
<div class="row g-4 mt-1"><div class="col-xl-8"><div class="card siget-card"><div class="card-header"><h2>Matriz ejecutiva</h2><p>Mayor cumplimiento y menor riesgo representan una mejor posición.</p></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Dirección</th><th>Cargas</th><th>Cierre</th><th>Vencidas</th><th>Lectura</th></tr></thead><tbody>@forelse($units->take(10) as $row)@php $pct=(float)($row['percentage']??0); $od=(int)($row['overdue']??0); @endphp<tr><td><strong>{{ $row['unit'] ?? 'Sin unidad' }}</strong></td><td>{{ $row['total'] ?? 0 }}</td><td>{{ $pct }}%</td><td>{{ $od }}</td><td><span class="badge {{ $od>0?'text-bg-warning':($pct>=80?'text-bg-success':'text-bg-secondary') }}">{{ $od>0?'Atención':($pct>=80?'Favorable':'Seguimiento') }}</span></td></tr>@empty<tr><td colspan="5" class="text-center py-4">Sin información para comparar.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><h2>Lectura para decisión</h2><p>Resumen de la situación actual.</p></div><div class="card-body vstack gap-3"><div><small class="text-muted">Desempeño</small><strong class="d-block">{{ $compliance }}% de cumplimiento</strong></div><div><small class="text-muted">Riesgo</small><strong class="d-block">{{ $overdue }} cargas vencidas</strong></div><div><small class="text-muted">Estabilidad</small><strong class="d-block">{{ $reprogrammed }} reprogramaciones</strong></div><div><small class="text-muted">Oportunidad</small><strong class="d-block">{{ $k['due_soon'] ?? 0 }} vencen en 72 horas</strong></div></div></div></div></div>

@elseif($role === 'ENLACE_INSTITUCIONAL')
<section class="siget-hero mb-4"><span class="badge text-bg-primary mb-2">Gestión institucional</span><h2>Centro de Revisión Institucional</h2><p>Seguimiento consolidado de avances, pendientes, observaciones y cierres de las dependencias asignadas.</p></section>
@include('dashboard.partials.filters')
<div class="row g-3 mb-4">@foreach([['Entregables',$total-1,'','bi-inboxes','primary'],['En operación',$active,'','bi-activity','info'],['Por revisar',$k['review_pending'] ?? 0,'','bi-clipboard-check','warning'],['Observados',$k['observed'] ?? 0,'','bi-chat-square-exclamation','danger'],['Reprogramados',$reprogrammed,'','bi-arrow-repeat','secondary'],['Cierre',$closureRate,'%','bi-patch-check','success']] as $card)<div class="col-6 col-xl-2"><div class="siget-kpi h-100"><div class="siget-kpi-icon text-bg-{{ $card[4] }}"><i class="bi {{ $card[3] }}"></i></div><div><small>{{ $card[0] }}</small><strong>{{ $card[1] }}{{ $card[2] }}</strong></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-7"><div class="card siget-card h-100"><div class="card-header"><h2>Avance por Dirección</h2><p>Comparación de volumen y cumplimiento.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleDirectionChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card siget-card h-100"><div class="card-header"><h2>Estado de revisión</h2><p>Distribución del trabajo institucional.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleStatusChart"></canvas></div></div></div></div><div class="col-xl-8"><div class="card siget-card h-100"><div class="card-header"><h2>Tendencia de entregas y cierres</h2><p>Permite anticipar acumulación de pendientes.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><h2>Dependencias con mayor presión</h2><p>Priorización para seguimiento.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleAgencyChart"></canvas></div></div></div></div></div>

@elseif($role === 'ADMINISTRADOR')
<section class="siget-hero mb-4"><span class="badge text-bg-dark mb-2">Administración SIGET</span><h2>Panel de Salud y Operación del Sistema</h2><p>Lectura de actividad, volumen de información, estados y calidad operativa. Sin modificar permisos ni procesos.</p></section>
@include('dashboard.partials.filters')
<div class="row g-3 mb-4">@foreach([['Cargas registradas',$total-1,'','bi-database','primary'],['Cargas activas',$active,'','bi-activity','info'],['Cerradas',$closed,'','bi-check-circle','success'],['Vencidas',$overdue,'','bi-exclamation-octagon','danger'],['Reprogramadas',$reprogrammed,'','bi-arrow-repeat','warning'],['Avance medio',$completion,'%','bi-speedometer2','secondary']] as $card)<div class="col-6 col-xl-2"><div class="siget-kpi h-100"><div class="siget-kpi-icon text-bg-{{ $card[4] }}"><i class="bi {{ $card[3] }}"></i></div><div><small>{{ $card[0] }}</small><strong>{{ $card[1] }}{{ $card[2] }}</strong></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-8"><div class="card siget-card h-100"><div class="card-header"><h2>Actividad del sistema</h2><p>Volumen de entradas y cierres por periodo.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><h2>Calidad del universo</h2><p>Distribución de estados que requieren control.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleStatusChart"></canvas></div></div></div></div><div class="col-xl-6"><div class="card siget-card h-100"><div class="card-header"><h2>Actividad por Dirección</h2><p>Concentración de información dentro del sistema.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleDirectionChart"></canvas></div></div></div></div><div class="col-xl-6"><div class="card siget-card h-100"><div class="card-header"><h2>Distribución por Dependencia</h2><p>Volumen y presión relativa del universo.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleAgencyChart"></canvas></div></div></div></div></div>

@elseif($role === 'DIRECTOR_TRANSMISION')
<section class="siget-hero mb-4"><span class="badge text-bg-primary mb-2">Operación · Transmisión</span><h2>Dashboard Operativo de Transmisión</h2><p>Solo indicadores de ejecución de la Dirección: carga de trabajo, cumplimiento, vencimientos, observaciones y reprogramaciones.</p></section>
@include('dashboard.partials.filters')
<div class="row g-3 mb-4">@foreach([['Cargas activas',$active,'','bi-broadcast-pin','primary'],['Pendientes',$k['review_pending'] ?? 0,'','bi-hourglass-split','warning'],['Vencidas',$overdue,'','bi-alarm','danger'],['Observadas',$k['observed'] ?? 0,'','bi-chat-square-exclamation','warning'],['Reprogramadas',$reprogrammed,'','bi-arrow-repeat','secondary'],['Cierre',$closureRate,'%','bi-check2-circle','success']] as $card)<div class="col-6 col-xl-2"><div class="siget-kpi h-100"><div class="siget-kpi-icon text-bg-{{ $card[4] }}"><i class="bi {{ $card[3] }}"></i></div><div><small>{{ $card[0] }}</small><strong>{{ $card[1] }}{{ $card[2] }}</strong></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-8"><div class="card siget-card h-100"><div class="card-header"><h2>Ritmo de ejecución</h2><p>Entradas, cierres y cumplimiento operativo de Transmisión.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><h2>Estado de cargas</h2><p>Distribución actual de la operación.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleStatusChart"></canvas></div></div></div></div><div class="col-xl-7"><div class="card siget-card h-100"><div class="card-header"><h2>Carga por unidad</h2><p>Volumen y vencimientos para actuar sobre la operación.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleDirectionChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card siget-card h-100"><div class="card-header"><h2>Presión por Dependencia</h2><p>Vencimientos y cumplimiento del alcance.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleAgencyChart"></canvas></div></div></div></div></div>

@elseif($role === 'DIRECTOR_PROGRAMACION_CONTINUIDAD')
<section class="siget-hero mb-4"><span class="badge text-bg-info mb-2">Operación · Programación y Continuidad</span><h2>Dashboard Operativo de Programación y Continuidad</h2><p>Indicadores de planeación y ejecución: programación, cumplimiento, carga futura, atrasos y reprogramaciones.</p></section>
@include('dashboard.partials.filters')
<div class="row g-3 mb-4">@foreach([['Programadas',$total-1,'','bi-calendar3','primary'],['En ejecución',$active,'','bi-play-circle','info'],['Pendientes',$k['review_pending'] ?? 0,'','bi-hourglass-split','warning'],['Vencidas',$overdue,'','bi-calendar-x','danger'],['Reprogramadas',$reprogrammed,'','bi-arrow-repeat','secondary'],['Cumplimiento',$compliance,'%','bi-check2-circle','success']] as $card)<div class="col-6 col-xl-2"><div class="siget-kpi h-100"><div class="siget-kpi-icon text-bg-{{ $card[4] }}"><i class="bi {{ $card[3] }}"></i></div><div><small>{{ $card[0] }}</small><strong>{{ $card[1] }}{{ $card[2] }}</strong></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-8"><div class="card siget-card h-100"><div class="card-header"><h2>Programado vs. ejecutado</h2><p>Evolución de la programación frente a los cierres.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><h2>Estado de programación</h2><p>Distribución de cargas por etapa.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleStatusChart"></canvas></div></div></div></div><div class="col-xl-7"><div class="card siget-card h-100"><div class="card-header"><h2>Cumplimiento por Dirección</h2><p>Comparación operativa de ejecución y vencimientos.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleDirectionChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card siget-card h-100"><div class="card-header"><h2>Reprogramación y presión</h2><p>Concentración de cargas que requieren ajuste.</p></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleAgencyChart"></canvas></div></div></div></div></div>

@else
<section class="siget-hero mb-4"><span class="badge text-bg-primary mb-2">{{ $presentation['scope'] ?? 'Mi alcance' }}</span><h2>{{ $presentation['title'] ?? 'Dashboard de seguimiento' }}</h2><p>{{ $presentation['subtitle'] ?? 'Estado de las cargas y evidencias dentro de su alcance autorizado.' }}</p></section>
@include('dashboard.partials.filters')
<div class="row g-3 mb-4">@foreach([['Avance medio',$completion,'%','bi-speedometer2','primary'],['Cargas activas',$active,'','bi-activity','info'],['Pendientes',$k['review_pending'] ?? 0,'','bi-hourglass-split','warning'],['Vencidas',$overdue,'','bi-alarm','danger'],['Reprogramadas',$reprogrammed,'','bi-arrow-repeat','secondary'],['Observadas',$k['observed'] ?? 0,'','bi-chat-square-exclamation','warning']] as $card)<div class="col-6 col-xl-2"><div class="siget-kpi h-100"><div class="siget-kpi-icon text-bg-{{ $card[4] }}"><i class="bi {{ $card[3] }}"></i></div><div><small>{{ $card[0] }}</small><strong>{{ $card[1] }}{{ $card[2] }}</strong></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-8"><div class="card siget-card"><div class="card-header"><h2>Evolución operativa</h2></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card siget-card"><div class="card-header"><h2>Estado de cargas</h2></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="roleStatusChart"></canvas></div></div></div></div></div>
@endif

<script type="application/json" data-siget-chart="roleTrendChart">{!! json_encode(['type'=>'line','labels'=>$monthly->pluck('period')->values(),'datasets'=>[['label'=>'Entradas','data'=>$monthly->pluck('total')->values()],['label'=>'Cierres','data'=>$monthly->pluck('closed')->values()],['label'=>'Cumplimiento %','data'=>$monthly->pluck('compliance')->values(),'yAxisID'=>'y1']]]) !!}</script>
<script type="application/json" data-siget-chart="roleStatusChart">{!! json_encode(['type'=>'doughnut','labels'=>array_keys($status),'datasets'=>[['label'=>'Cargas','data'=>array_values($status)] ]]) !!}</script>
<script type="application/json" data-siget-chart="roleDirectionChart">{!! json_encode(['type'=>'bar','labels'=>$units->pluck('unit')->values(),'datasets'=>[['label'=>'Cumplimiento %','data'=>$units->pluck('percentage')->values()],['label'=>'Vencidas','data'=>$units->pluck('overdue')->values()] ]]) !!}</script>
<script type="application/json" data-siget-chart="roleAgencyChart">{!! json_encode(['type'=>'bar','labels'=>$agencies->pluck('agency')->values(),'datasets'=>[['label'=>'Vencidas','data'=>$agencies->pluck('overdue')->values()],['label'=>'Cumplimiento %','data'=>$agencies->pluck('percentage')->values()] ]]) !!}</script>
@endsection
