@extends('layouts.app')
@section('title','Dashboard SIGET')
@section('page-title', $presentation['title'] ?? 'Dashboard SIGET')
@section('page-subtitle', $presentation['subtitle'] ?? 'Información de SIGET')
@section('content')
@php
$role = auth()->user()?->role?->code;
$k = $analytics['kpis'] ?? [];
$filters = $filters ?? [];
$monthly = collect($analytics['monthly_trend'] ?? []);
$units = collect($analytics['unit_performance'] ?? $analytics['direction_performance'] ?? []);
$agencies = collect($analytics['agency_performance'] ?? []);
$status = collect($analytics['status_distribution'] ?? []);
$executiveStatus = $status->only(['REPROGRAMADA','VENCIDA','VALIDADO_Y_CERRADO']);
$total = (int)($k['total'] ?? 0);
$closed = (int)($k['closed'] ?? 0);
$overdue = (int)($k['overdue'] ?? 0);
$active = (int)($k['active'] ?? 0);
$reprogrammed = (int)($k['reprogrammed'] ?? 0);
$completion = (float)($k['completion_average'] ?? 0);
$compliance = (float)($k['compliance'] ?? 0);
$closureRate = $total ? round(100*$closed/$total,1) : 0;
$riskRate = $total ? round(100*$overdue/$total,1) : 0;
$reprogramRate = $total ? round(100*$reprogrammed/$total,1) : 0;
$monthlyLabels = $monthly->pluck('period')->values();
@endphp
<style>
.siget-exec{--line:rgba(255,255,255,.09);--text:#f4f8fb;--muted:#8fa4b7;--cyan:#21c6d8;--blue:#4f7cff;--green:#35c77a;--yellow:#e9b949;--red:#ef4655;background:linear-gradient(180deg,#09131f,#0b1119);border:1px solid var(--line);border-radius:18px;padding:18px;color:var(--text)}
.siget-exec .hero{background:linear-gradient(100deg,#0e2533,#10283b 55%,#0d1a27);border:1px solid rgba(33,198,216,.22);border-radius:16px;padding:20px 22px;margin-bottom:16px}.siget-exec .eyebrow{font-size:.7rem;text-transform:uppercase;letter-spacing:.12em;color:#69d8e4;font-weight:700}.siget-exec h2{color:#fff;font-weight:700}.siget-exec .muted{color:var(--muted)}
.siget-exec .kpi{background:linear-gradient(145deg,#111e2b,#0e1823);border:1px solid var(--line);border-radius:14px;padding:16px;min-height:116px;position:relative;overflow:hidden}.siget-exec .kpi:after{content:"";position:absolute;left:0;right:0;bottom:0;height:3px;background:var(--accent,#21c6d8);opacity:.85}.siget-exec .kpi .icon{width:34px;height:34px;border-radius:9px;display:grid;place-items:center;background:rgba(33,198,216,.12);color:var(--accent,#21c6d8);margin-bottom:10px}.siget-exec .kpi small{display:block;color:var(--muted);font-size:.72rem}.siget-exec .kpi strong{display:block;font-size:1.55rem;line-height:1.1;margin-top:3px}.siget-exec .delta{font-size:.68rem;margin-top:7px;color:#76d69d}.siget-exec .mini{font-size:.68rem;color:var(--muted)}
.siget-exec .panel{background:rgba(16,29,42,.92);border:1px solid var(--line);border-radius:15px;overflow:hidden;height:100%}.siget-exec .panel-head{padding:15px 17px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:12px}.siget-exec .panel-head h3{font-size:.95rem;margin:0;color:#fff}.siget-exec .panel-head p{font-size:.67rem;margin:4px 0 0;color:var(--muted)}.siget-exec .chart{height:300px;padding:10px 14px 12px}.siget-exec .chart canvas{width:100%!important;height:100%!important}.siget-exec .table{--bs-table-bg:transparent;--bs-table-color:#eaf2f7;--bs-table-border-color:var(--line);font-size:.72rem;margin:0}.siget-exec .table th{color:#7890a3;font-size:.61rem;text-transform:uppercase;letter-spacing:.04em}.siget-exec .table td,.siget-exec .table th{padding:9px 10px}.siget-exec .decision{padding:12px}.siget-exec .decision-item{display:flex;gap:11px;padding:11px 0;border-bottom:1px solid var(--line)}.siget-exec .decision-item:last-child{border-bottom:0}.siget-exec .decision-dot{width:10px;height:10px;border-radius:50%;margin-top:5px;background:var(--dot,#35c77a);box-shadow:0 0 12px var(--dot,#35c77a)}.siget-exec .decision-item strong{display:block;color:#fff;font-size:.8rem}.siget-exec .decision-item span{display:block;color:var(--muted);font-size:.68rem;margin-top:3px}.siget-exec .badge-exec{font-size:.58rem;padding:4px 6px;border-radius:7px}.siget-exec .filter-note{font-size:.68rem;color:var(--muted);margin-bottom:12px}
.siget-role{background:linear-gradient(180deg,#0b1118,#101820);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:18px}.siget-role .role-title{font-size:1.3rem;color:#fff;font-weight:700}.siget-role .role-sub{color:#93a6b6;font-size:.76rem}.siget-role .role-card{background:#121b24;border:1px solid rgba(255,255,255,.08);border-radius:13px;padding:15px;height:100%}.siget-role .role-card small{color:#91a5b7}.siget-role .role-card strong{font-size:1.35rem;color:#fff;display:block;margin-top:5px}.siget-role .role-chart{height:250px}.siget-role .role-chart canvas{width:100%!important;height:100%!important}
</style>

@if($role === 'DIRECTOR_GENERAL')
<div class="siget-exec">
<div class="hero d-flex justify-content-between align-items-start gap-3"><div><div class="eyebrow">Dirección General · Visión estratégica</div><h2 class="mb-1">Centro Ejecutivo Institucional</h2><div class="muted">Situación global, desempeño, riesgo y tendencia. No contiene bandejas ni rutas operativas.</div></div><div class="text-end"><div class="mini">UNIVERSO ANALIZADO</div><strong class="fs-4">{{ number_format($total) }}</strong><div class="mini">cargas</div></div></div>
@include('dashboard.partials.filters')
<div class="filter-note">Los filtros acotan el universo y todas las gráficas se recalculan sobre la selección.</div>
<div class="row g-3 mb-3">@foreach([['Cumplimiento institucional',$compliance,'%','bi-check2-circle','#35c77a','lectura institucional'],['Avance medio',$completion,'%','bi-speedometer2','#4f7cff','avance del universo'],['Cierre efectivo',$closureRate,'%','bi-patch-check','#21c6d8','cierres validados'],['Presión de riesgo',$riskRate,'%','bi-exclamation-triangle','#ef4655','vencimiento relativo'],['Estabilidad operativa',max(0,100-$reprogramRate),'%','bi-graph-up-arrow','#e9b949','reprogramación relativa'],['Cargas activas',$active,'','bi-activity','#9aa8b5','universo en operación']] as $card)<div class="col-6 col-xl-2"><div class="kpi" style="--accent:{{ $card[4] }}"><div class="icon"><i class="bi {{ $card[3] }}"></i></div><small>{{ $card[0] }}</small><strong>{{ $card[1] }}{{ $card[2] }}</strong><div class="delta">{{ $card[5] }}</div></div></div>@endforeach</div>
<div class="row g-3">
<div class="col-xl-5"><div class="panel"><div class="panel-head"><div><h3>Tendencia institucional</h3><p>Evolución del trabajo: entradas, cierres y cumplimiento.</p></div><span class="mini">Periodo seleccionado</span></div><div class="chart"><canvas id="roleTrendChart"></canvas></div></div></div>
<div class="col-xl-3"><div class="panel"><div class="panel-head"><div><h3>Composición institucional por estado</h3><p>Distribución del universo actual.</p></div></div><div class="chart"><canvas id="roleStatusChart"></canvas></div></div></div>
<div class="col-xl-4"><div class="panel"><div class="panel-head"><div><h3>Desempeño comparativo por Dirección</h3><p>Cargas y cumplimiento.</p></div></div><div class="chart"><canvas id="roleDirectionChart"></canvas></div></div></div>
<div class="col-xl-4"><div class="panel"><div class="panel-head"><div><h3>Concentración de riesgo por Dependencia</h3><p>Vencimientos y % de riesgo para localizar presión.</p></div></div><div class="chart"><canvas id="roleAgencyChart"></canvas></div></div></div>
<div class="col-xl-4"><div class="panel"><div class="panel-head"><div><h3>Matriz ejecutiva de desempeño</h3><p>Lectura por Dirección para decisión.</p></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Dirección / Unidad</th><th>Cargas</th><th>Cumpl.</th><th>Cierre</th><th>Venc.</th><th>Lectura</th></tr></thead><tbody>@forelse($units->take(8) as $row)@php $pct=(float)($row['percentage']??0); $od=(int)($row['overdue']??0); $rt=(int)($row['total']??0); $cl=(int)($row['closed']??0); $cr=$rt?round(100*$cl/$rt,1):0; @endphp<tr><td><strong>{{ $row['unit'] ?? 'Sin unidad' }}</strong></td><td>{{ $rt }}</td><td>{{ $pct }}%</td><td>{{ $cr }}%</td><td>{{ $od }}</td><td><span class="badge-exec {{ $od>0?'bg-danger':($pct>=80?'bg-success':'bg-warning text-dark') }}">{{ $od>0?'ATENCIÓN':($pct>=80?'FAVORABLE':'SEGUIMIENTO') }}</span></td></tr>@empty<tr><td colspan="6" class="text-center py-4">Sin información para comparar.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-xl-4"><div class="panel"><div class="panel-head"><div><h3>Lectura para Dirección General</h3><p>Resumen ejecutivo para toma de decisiones.</p></div></div><div class="decision"><div class="decision-item" style="--dot:#35c77a"><i class="decision-dot"></i><div><strong>El cumplimiento institucional</strong><span>{{ $compliance }}% sobre {{ number_format($total) }} cargas, con tendencia del periodo seleccionado.</span></div></div><div class="decision-item" style="--dot:#e9b949"><i class="decision-dot"></i><div><strong>La brecha de desempeño</strong><span>{{ $units->filter(fn($u)=>(float)($u['percentage']??0)<80)->count() }} Dirección(es) requieren seguimiento por debajo de 80%.</span></div></div><div class="decision-item" style="--dot:#ef4655"><i class="decision-dot"></i><div><strong>La presión de riesgo</strong><span>{{ $overdue }} cargas vencidas representan {{ $riskRate }}% del universo y se concentran por dependencia.</span></div></div><div class="decision-item" style="--dot:#4f7cff"><i class="decision-dot"></i><div><strong>La oportunidad inmediata</strong><span>{{ $k['due_soon'] ?? 0 }} cargas vencen en las próximas 72 horas; priorizar donde coincidan vencimiento y bajo cumplimiento.</span></div></div></div></div></div>
</div></div>
@else
<div class="siget-role"><div class="mb-3"><div class="role-title">{{ $presentation['title'] ?? 'Dashboard SIGET' }}</div><div class="role-sub">{{ $presentation['subtitle'] ?? 'Indicadores del sistema' }}</div></div>
@include('dashboard.partials.filters')
@php $roleCards = match($role) {'ENLACE_INSTITUCIONAL'=>[['Entregables',$total],['En operación',$active],['Por revisar',$k['review_pending']??0],['Observados',$k['observed']??0],['Reprogramados',$reprogrammed],['Cierre',$closureRate.'%']], 'ADMINISTRADOR'=>[['Cargas registradas',$total],['Activas',$active],['Cerradas',$closed],['Vencidas',$overdue],['Reprogramadas',$reprogrammed],['Avance medio',$completion.'%']], 'DIRECTOR_TRANSMISION'=>[['Cargas activas',$active],['Pendientes',$k['review_pending']??0],['Vencidas',$overdue],['Observadas',$k['observed']??0],['Reprogramadas',$reprogrammed],['Cierre',$closureRate.'%']], 'DIRECTOR_PROGRAMACION_CONTINUIDAD'=>[['Programadas',$total],['En ejecución',$active],['Pendientes',$k['review_pending']??0],['Vencidas',$overdue],['Reprogramadas',$reprogrammed],['Cumplimiento',$compliance.'%']], default=>[['Total',$total],['Activas',$active],['Cerradas',$closed],['Vencidas',$overdue],['Reprogramadas',$reprogrammed],['Cumplimiento',$compliance.'%']]} @endphp
<div class="row g-3 mb-3">@foreach($roleCards as $card)<div class="col-6 col-xl-2"><div class="role-card"><small>{{ $card[0] }}</small><strong>{{ $card[1] }}</strong></div></div>@endforeach</div>
<div class="row g-3"><div class="col-xl-7"><div class="role-card"><div class="role-title fs-6">{{ $role==='DIRECTOR_PROGRAMACION_CONTINUIDAD'?'Planeación vs ejecución':'Ritmo de operación' }}</div><div class="role-sub mb-2">Entradas, ejecución, cierres y cumplimiento.</div><div class="role-chart"><canvas id="roleTrendChart"></canvas></div></div></div><div class="col-xl-5"><div class="role-card"><div class="role-title fs-6">Estado operativo</div><div class="role-sub mb-2">Distribución actual de estados.</div><div class="role-chart"><canvas id="roleStatusChart"></canvas></div></div></div><div class="col-xl-6"><div class="role-card"><div class="role-title fs-6">{{ $role==='DIRECTOR_TRANSMISION'?'Carga por unidad':'Avance por Dirección' }}</div><div class="role-sub mb-2">Volumen y cumplimiento.</div><div class="role-chart"><canvas id="roleDirectionChart"></canvas></div></div></div><div class="col-xl-6"><div class="role-card"><div class="role-title fs-6">Presión por Dependencia</div><div class="role-sub mb-2">Vencimientos y comportamiento.</div><div class="role-chart"><canvas id="roleAgencyChart"></canvas></div></div></div></div></div>
@endif
<script>
(function(){const monthly=@json($monthlyLabels),totals=@json($monthly->pluck('total')->values()),closed=@json($monthly->pluck('closed')->values()),comp=@json($monthly->pluck('compliance')->values()),units=@json($units->take(10)->values()),agencies=@json($agencies->take(10)->values()),rawStatus=@json($status),executiveStatus=@json($executiveStatus);const text='#eaf2f7',muted='#8195a8',grid='rgba(255,255,255,.08)',cyan='#21c6d8',blue='#4f7cff',green='#35c77a',red='#ef4655',yellow='#e9b949';function c(id,type,data,opts={}){const el=document.getElementById(id);if(!el||typeof Chart==='undefined')return;new Chart(el,{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:text,boxWidth:10,font:{size:10}}}},scales:{x:{ticks:{color:muted,font:{size:9}},grid:{color:grid}},y:{ticks:{color:muted,font:{size:9}},grid:{color:grid},beginAtZero:true}},...opts}})}
const executive=!!document.querySelector('.siget-exec');
c('roleTrendChart','line',{labels:monthly,datasets:[{label:'Entradas',data:totals,borderColor:cyan,tension:.35,borderWidth:2,fill:false},{label:'Cierres',data:closed,borderColor:blue,tension:.35,borderWidth:2,fill:false},{label:'Cumplimiento %',data:comp,borderColor:green,tension:.35,borderWidth:2,yAxisID:'y1',fill:false}]},{scales:{x:{ticks:{color:muted},grid:{color:grid}},y:{ticks:{color:muted},grid:{color:grid},beginAtZero:true},y1:{position:'right',min:0,max:100,ticks:{color:muted},grid:{drawOnChartArea:false}}}});
const s=executive
? {'Reprogramadas':Number(executiveStatus.REPROGRAMADA||0),'Vencidas':Number(executiveStatus.VENCIDA||0),'Validadas y cerradas':Number(executiveStatus.VALIDADO_Y_CERRADO||0)}
: (()=>{const x={};Object.entries(rawStatus).forEach(([k,v])=>{let n=k==='VALIDADO_Y_CERRADO'?'Cerradas':k==='VENCIDA'?'Vencidas':(['OBSERVADA','EN_REVISION_INSTITUCIONAL'].includes(k)?'En revisión':(['REPROGRAMADA','REPROGRAMADA_ABIERTA','REPROGRAMADA_ENTREGADA','SUSPENDIDA'].includes(k)?'Reprogramadas':'En operación'));x[n]=(x[n]||0)+Number(v)});return x;})();c('roleStatusChart','doughnut',{labels:Object.keys(s),datasets:[{data:Object.values(s),backgroundColor:[green,blue,yellow,red,cyan],borderWidth:0}]},{cutout:'68%',plugins:{legend:{position:'bottom',labels:{color:text,boxWidth:9,font:{size:9}}}}});
if(executive){c('roleDirectionChart','bar',{labels:units.map(x=>x.unit||x.name||'Sin unidad'),datasets:[{type:'bar',label:'Cargas',data:units.map(x=>Number(x.total||0)),backgroundColor:cyan,borderRadius:5,yAxisID:'y'},{type:'line',label:'Cumplimiento %',data:units.map(x=>Number(x.percentage||0)),borderColor:yellow,backgroundColor:yellow,tension:.25,borderWidth:2,pointRadius:3,yAxisID:'y1'}]},{scales:{x:{ticks:{color:muted,font:{size:9}},grid:{color:grid}},y:{beginAtZero:true,ticks:{color:muted},grid:{color:grid}},y1:{position:'right',min:0,max:100,ticks:{color:muted},grid:{drawOnChartArea:false}}},plugins:{legend:{position:'bottom',labels:{color:text,boxWidth:9,font:{size:9}}}}});const riskLabels=agencies.map(x=>x.agency||'Sin dependencia'),riskCounts=agencies.map(x=>Number(x.overdue||0)),riskPct=agencies.map(x=>{const t=Number(x.total||0);return t?Number((100*Number(x.overdue||0)/t).toFixed(1)):0});c('roleAgencyChart','bar',{labels:riskLabels,datasets:[{type:'bar',label:'Vencidas',data:riskCounts,backgroundColor:red,borderRadius:4,yAxisID:'y'},{type:'line',label:'% Vencidas',data:riskPct,borderColor:blue,backgroundColor:blue,tension:.25,borderWidth:2,pointRadius:3,yAxisID:'y1'}]},{scales:{x:{ticks:{color:muted,font:{size:9}},grid:{color:grid}},y:{beginAtZero:true,ticks:{color:muted},grid:{color:grid}},y1:{position:'right',min:0,max:100,ticks:{color:muted},grid:{drawOnChartArea:false}}},plugins:{legend:{position:'bottom',labels:{color:text,boxWidth:9,font:{size:9}}}}});}else{c('roleDirectionChart','bar',{labels:units.map(x=>x.unit||x.name||'Sin unidad'),datasets:[{label:'Cargas',data:units.map(x=>Number(x.total||0)),backgroundColor:cyan,borderRadius:5},{label:'Cumplimiento %',data:units.map(x=>Number(x.percentage||0)),backgroundColor:blue,borderRadius:5}]},{plugins:{legend:{position:'bottom',labels:{color:text,boxWidth:9,font:{size:9}}}}});c('roleAgencyChart','bar',{labels:agencies.map(x=>x.agency||'Sin dependencia'),datasets:[{label:'Vencidas',data:agencies.map(x=>Number(x.overdue||0)),backgroundColor:red,borderRadius:5},{label:'Cumplimiento %',data:agencies.map(x=>Number(x.percentage||0)),backgroundColor:yellow,borderRadius:5}]},{indexAxis:'y',plugins:{legend:{position:'bottom',labels:{color:text,boxWidth:9,font:{size:9}}}}});}})();
</script>
@endsection
