@extends('layouts.app')
@section('title', request()->routeIs('loads.mine') ? 'Mis cargas' : 'Repositorio')
@section('page-title', request()->routeIs('loads.mine') ? 'Mis cargas' : 'Repositorio institucional de evidencias')
@section('page-subtitle', request()->routeIs('loads.mine') ? 'Cargas de su alcance con captura directa de evidencias por dirección.' : 'Navegación por dependencia, periodo, dirección y carga programada.')
@section('content')
<div class="siget-file-manager" data-file-manager>
<aside class="siget-file-sidebar"><div class="siget-storage-card"><div class="d-flex justify-content-between"><strong>Almacenamiento visible</strong><i class="bi bi-database"></i></div><div class="progress mt-3"><div class="progress-bar" style="width:{{ min(100,round($usedBytes/max(1,10*1024*1024*1024)*100,1)) }}%"></div></div><small class="text-secondary">{{ number_format($usedBytes/1024/1024,1) }} MB en archivos de su alcance</small><div class="siget-folder-tree"><a href="{{ route('repository.index') }}" class="{{ empty($filters['agency_id'])?'active':'' }}"><i class="bi bi-folder2-open"></i>Todo el repositorio<span>{{ $loads->total() }}</span></a>@foreach($agencies as $a)<a href="{{ route('repository.index',['agency_id'=>$a->id]) }}" class="{{ (int)($filters['agency_id']??0)===$a->id?'active':'' }}"><i class="bi bi-building"></i>{{ $a->name }}<span>{{ $agencyCounts[$a->id] ?? 0 }}</span></a>@endforeach</div></div></aside>
<section class="card siget-card"><div class="siget-file-toolbar"><div><div class="small text-secondary">SIGET / {{ request()->routeIs('loads.mine') ? 'Mis cargas' : 'Repositorio' }} @if(!empty($filters['agency_id']))/ {{ $agencies->firstWhere('id',(int)$filters['agency_id'])?->name }}@endif</div><strong>{{ request()->routeIs('loads.mine') ? 'Cargas y captura de evidencias' : 'Expedientes y archivos' }}</strong></div><div class="d-flex gap-2"><form method="GET" class="d-flex gap-2"><input type="hidden" name="agency_id" value="{{ $filters['agency_id']??'' }}"><input class="form-control" name="q" value="{{ $filters['q']??'' }}" placeholder="Buscar archivos o cargas"><button class="btn btn-primary"><i class="bi bi-search"></i></button></form><div class="btn-group"><button class="btn btn-outline-secondary" data-file-view="grid"><i class="bi bi-grid"></i></button><button class="btn btn-outline-secondary" data-file-view="list"><i class="bi bi-list"></i></button></div></div></div>
<div class="siget-file-section"><h2>Carpetas de cargas programadas</h2><div class="siget-folder-grid">@forelse($loads as $load)<a href="{{ route('loads.show',$load) }}" class="siget-folder-card"><i class="bi bi-folder-fill"></i><strong>{{ $load->title }}</strong><small>{{ $load->agency?->name }}</small><small>{{ $load->period_label }} · {{ $load->effective_open_at?->format('d/m/Y') }}</small><small>{{ $load->deliverables->sum(fn($d)=>$d->evidences->sum(fn($e)=>$e->files->count())) }} archivos · {{ $load->completion_percentage }}%</small></a>@empty<div class="text-secondary">No existen carpetas dentro del filtro seleccionado.</div>@endforelse</div><div class="mt-3">{{ $loads->links() }}</div></div>
@if(auth()->user()->hasPermission('evidence.upload'))
<div class="siget-file-section border-top"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="mb-1">Adjuntar evidencias desde Mis cargas</h2><p class="text-secondary mb-0">Cada archivo queda ligado a su carga y a la carpeta individual de la dirección autorizada; también aparece en el repositorio institucional general.</p></div><span class="badge text-bg-light"><i class="bi bi-shield-lock me-1"></i>Alcance por dirección</span></div>
@forelse($loads as $load)
<div class="card border mb-3"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2"><div><strong>{{ $load->title }}</strong><div class="small text-secondary">{{ $load->agency?->name }} · {{ $load->period_label }}</div></div><a href="{{ route('loads.show',$load) }}" class="btn btn-sm btn-outline-primary">Abrir expediente</a></div><div class="card-body"><div class="row g-3">
@forelse($load->deliverables as $deliverable)
@php($evidence = $deliverable->evidences->sortByDesc('id')->first())
<div class="col-xl-6"><div class="border rounded p-3 h-100"><div class="d-flex justify-content-between gap-2 mb-2"><div><span class="badge text-bg-light"><i class="bi bi-diagram-3 me-1"></i>{{ $deliverable->organizationalUnit?->name }}</span><h3 class="h6 mt-2 mb-1">{{ $deliverable->templateRequirement?->name }}</h3><small class="text-secondary">Formatos: {{ implode(', ', $deliverable->templateRequirement?->allowed_extensions ?? []) }}</small></div><span class="badge siget-status">{{ $deliverable->status instanceof \BackedEnum ? $deliverable->status->value : $deliverable->status }}</span></div>
@if($evidence)<div class="small mb-2"><strong>{{ $evidence->title }}</strong> · V{{ $evidence->current_version }} <span class="text-secondary">({{ $evidence->files->count() }} archivo(s))</span></div><a href="{{ route('evidences.show',$evidence) }}" class="btn btn-sm btn-outline-secondary mb-3">Ver evidencia y versiones</a>@endif
<form action="{{ route('evidences.store') }}" method="POST" enctype="multipart/form-data">@csrf<input type="hidden" name="deliverable_id" value="{{ $deliverable->id }}"><div class="mb-2"><input name="title" class="form-control" placeholder="Título de la evidencia" value="{{ $evidence?->title }}"></div><div class="input-group"><input name="file" type="file" class="form-control" required><button class="btn btn-primary"><i class="bi bi-paperclip me-1"></i>Adjuntar evidencia</button></div></form><div class="small text-secondary mt-2"><i class="bi bi-folder2-open me-1"></i>Repositorio individual: {{ $deliverable->organizationalUnit?->name }}</div></div></div>
@empty<div class="col-12 text-secondary">No hay entregables de su dirección en esta carga.</div>@endforelse
</div></div></div>
@empty<div class="text-secondary">No hay cargas disponibles para adjuntar evidencias.</div>@endforelse
</div>
@endif
<div class="siget-file-section border-top"><h2>Archivos recientes</h2><div class="siget-file-grid">@forelse($recentFiles as $f)<a href="{{ route('evidence-files.download',$f) }}" class="siget-file-card"><i class="bi {{ in_array(strtolower($f->extension),['pdf'])?'bi-file-earmark-pdf':(in_array(strtolower($f->extension),['xlsx','xls','csv'])?'bi-file-earmark-spreadsheet':'bi-file-earmark') }}"></i><span><strong>{{ $f->original_name }}</strong><small>{{ $f->evidence?->scheduledLoad?->agency?->name }}</small></span><small>{{ number_format($f->size_bytes/1024,1) }} KB</small><small>{{ $f->created_at?->format('d/m/Y H:i') }}</small></a>@empty<div class="text-secondary">No hay archivos recientes.</div>@endforelse</div></div></section></div>
@endsection
