@extends('layouts.app')
@section('title','Repositorio')
@section('page-title','Repositorio institucional de evidencias')
@section('page-subtitle','Navegación por dependencia, periodo, dirección y carga programada.')
@section('content')
<div class="siget-file-manager" data-file-manager>
<aside class="siget-file-sidebar"><div class="siget-storage-card"><div class="d-flex justify-content-between"><strong>Almacenamiento visible</strong><i class="bi bi-database"></i></div><div class="progress mt-3"><div class="progress-bar" style="width:{{ min(100,round($usedBytes/max(1,10*1024*1024*1024)*100,1)) }}%"></div></div><small class="text-secondary">{{ number_format($usedBytes/1024/1024,1) }} MB en archivos de su alcance</small><div class="siget-folder-tree"><a href="{{ route('repository.index') }}" class="{{ empty($filters['agency_id'])?'active':'' }}"><i class="bi bi-folder2-open"></i>Todo el repositorio<span>{{ $loads->total() }}</span></a>@foreach($agencies as $a)<a href="{{ route('repository.index',['agency_id'=>$a->id]) }}" class="{{ (int)($filters['agency_id']??0)===$a->id?'active':'' }}"><i class="bi bi-building"></i>{{ $a->name }}<span>{{ $agencyCounts[$a->id] ?? 0 }}</span></a>@endforeach</div></div></aside>
<section class="card siget-card"><div class="siget-file-toolbar"><div><div class="small text-secondary">SIGET / Repositorio @if(!empty($filters['agency_id']))/ {{ $agencies->firstWhere('id',(int)$filters['agency_id'])?->name }}@endif</div><strong>Expedientes y archivos</strong></div><div class="d-flex gap-2"><form method="GET" class="d-flex gap-2"><input type="hidden" name="agency_id" value="{{ $filters['agency_id']??'' }}"><input class="form-control" name="q" value="{{ $filters['q']??'' }}" placeholder="Buscar archivos o cargas"><button class="btn btn-primary"><i class="bi bi-search"></i></button></form><div class="btn-group"><button class="btn btn-outline-secondary" data-file-view="grid"><i class="bi bi-grid"></i></button><button class="btn btn-outline-secondary" data-file-view="list"><i class="bi bi-list"></i></button></div></div></div>
<div class="siget-file-section"><h2>Carpetas de cargas programadas</h2><div class="siget-folder-grid">@forelse($loads as $load)<a href="{{ route('loads.show',$load) }}" class="siget-folder-card"><i class="bi bi-folder-fill"></i><strong>{{ $load->title }}</strong><small>{{ $load->agency?->name }}</small><small>{{ $load->period_label }} · {{ $load->effective_open_at?->format('d/m/Y') }}</small><small>{{ $load->deliverables->sum(fn($d)=>$d->evidences->sum(fn($e)=>$e->files->count())) }} archivos · {{ $load->completion_percentage }}%</small></a>@empty<div class="text-secondary">No existen carpetas dentro del filtro seleccionado.</div>@endforelse</div><div class="mt-3">{{ $loads->links() }}</div></div>
<div class="siget-file-section border-top"><h2>Archivos recientes</h2><div class="siget-file-grid">@forelse($recentFiles as $f)<a href="{{ route('evidence-files.download',$f) }}" class="siget-file-card"><i class="bi {{ in_array(strtolower($f->extension),['pdf'])?'bi-file-earmark-pdf':(in_array(strtolower($f->extension),['xlsx','xls','csv'])?'bi-file-earmark-spreadsheet':'bi-file-earmark') }}"></i><span><strong>{{ $f->original_name }}</strong><small>{{ $f->evidence?->scheduledLoad?->agency?->name }}</small></span><small>{{ number_format($f->size_bytes/1024,1) }} KB</small><small>{{ $f->created_at?->format('d/m/Y H:i') }}</small></a>@empty<div class="text-secondary">No hay archivos recientes.</div>@endforelse</div></div></section></div>
@endsection
