<!doctype html><html lang="es"><head><meta charset="utf-8"><style>
@page{size:A4 landscape;margin:18px 22px}body{font-family:DejaVu Sans,sans-serif;font-size:7px;color:#243247;margin:0}h1,h2,h3,p{margin:0}h1{font-size:17px}h2{font-size:11px;margin:10px 0 5px}h3{font-size:8px}.head{background:#10213b;color:#fff;padding:10px 12px;border-radius:5px;margin-bottom:7px}.head h1{color:#fff}.head p{color:#d8e1ec;margin-top:2px}.meta,.kpi,.tbl{width:100%;border-collapse:collapse}.meta{margin-top:6px}.meta td{border:1px solid #52637b;padding:4px;font-size:6.5px}.meta b{display:block;color:#b9c8dc;font-size:5.5px}.kpi{margin:0 0 7px}.kpi td{width:16.66%;border:1px solid #d6dde7;background:#f5f7fa;padding:5px;text-align:center}.kpi .lab{font-size:5.5px;color:#69778a;text-transform:uppercase}.kpi strong{font-size:12px;color:#10213b}.sec{border:1px solid #d8dee7;border-radius:4px;overflow:hidden;margin-bottom:7px}.title{background:#10213b;color:#fff;padding:5px 7px;font-size:7px;font-weight:bold}.sub{background:#f0f3f7;color:#5f6d80;padding:4px 7px;font-size:5.8px}.tbl{font-size:6.1px}.tbl th{background:#15263f;color:#fff;padding:4px;text-align:left;font-size:5.5px;text-transform:uppercase}.tbl td{padding:4px;border:1px solid #e0e5ec}.center{text-align:center}.badge{padding:2px 4px;border-radius:5px;font-size:5px;font-weight:bold}.ok{background:#e7f6ee;color:#127a49}.warn{background:#fff4d7;color:#966700}.danger{background:#fdeaea;color:#a82d2d}.group{border:1px solid #cfd7e2;border-radius:4px;overflow:hidden;margin-bottom:6px}.group h3{background:#e9eef4;color:#10213b;padding:5px 7px}.group .gsub{background:#f7f9fb;padding:4px 7px;border-top:1px solid #dbe1e9;border-bottom:1px solid #dbe1e9;font-size:5.7px;font-weight:bold}.foot{margin-top:8px;border-top:1px solid #d7dee8;padding-top:4px;color:#758194;font-size:5.5px}.break{page-break-before:always}
</style></head><body>
@php
$k=$analytics['kpis']??[];$status=collect($analytics['status_distribution']??[]);$agencies=collect($analytics['agency_performance']??[]);$units=collect($analytics['unit_performance']??[]);$monthly=collect($analytics['monthly_trend']??[]);$states=['PROGRAMADA'=>'PROGRAMADO','REPROGRAMADA'=>'REPROGRAMADO','VALIDADO_Y_CERRADO'=>'VALIDADO Y CERRADO','VENCIDA'=>'VENCIDO'];
@endphp
<div class="head"><div style="font-size:5.5px;letter-spacing:1px;text-transform:uppercase;color:#b9c8dc">SIGET · Reporte Ejecutivo · A4 Horizontal</div><h1>Reporte Ejecutivo Institucional</h1><p>Dependencia → Dirección / Unidad → desempeño.</p><table class="meta"><tr><td><b>Periodo</b>{{ ($analytics['period_min']??null)?:'Universo actual' }} @if(!empty($analytics['period_max'])) → {{ $analytics['period_max'] }} @endif</td><td><b>Generado por</b>{{ $generatedBy->name }}</td><td><b>Emisión</b>{{ now()->format('d/m/Y H:i') }}</td><td><b>Universo</b>{{ number_format((int)($k['total']??0)) }} cargas</td></tr></table></div>
<table class="kpi"><tr><td><div class="lab">Total</div><strong>{{ number_format((int)($k['total']??0)) }}</strong></td><td><div class="lab">Activas</div><strong>{{ number_format((int)($k['active']??0)) }}</strong></td><td><div class="lab">Cerradas</div><strong>{{ number_format((int)($k['closed']??0)) }}</strong></td><td><div class="lab">Vencidas</div><strong>{{ number_format((int)($k['overdue']??0)) }}</strong></td><td><div class="lab">Reprogramadas</div><strong>{{ number_format((int)($k['reprogrammed']??0)) }}</strong></td><td><div class="lab">Cumplimiento</div><strong>{{ number_format((float)($k['compliance']??0),1) }}%</strong></td></tr></table>
<div class="sec"><div class="title">1 · Estados oficiales</div><div class="sub">PROGRAMADO · REPROGRAMADO · VALIDADO Y CERRADO · VENCIDO</div><table class="tbl"><thead><tr>@foreach($states as $code=>$label)<th>{{ $label }}</th>@endforeach</tr></thead><tbody><tr>@foreach($states as $code=>$label)<td class="center"><strong>{{ (int)($status[$code]??0) }}</strong></td>@endforeach</tr></tbody></table></div>
<div class="sec"><div class="title">2 · Cumplimiento por Dependencia</div><table class="tbl"><thead><tr><th>Dependencia</th><th class="center">Cargas</th><th class="center">Cerradas</th><th class="center">Vencidas</th><th class="center">Reprogramadas</th><th class="center">Cumplimiento</th></tr></thead><tbody>@foreach($agencies as $r) @php $pct=(float)($r['percentage']??0);$late=(int)($r['overdue']??0);$label=$late>0?'INCUMPLIMIENTO':($pct>=90?'EN CUMPLIMIENTO':'ATENCIÓN');$bc=$late>0?'danger':($pct>=90?'ok':'warn'); @endphp<tr><td><strong>{{ $r['agency']??'Sin dependencia' }}</strong></td><td class="center">{{ $r['total']??0 }}</td><td class="center">{{ $r['closed']??0 }}</td><td class="center">{{ $late }}</td><td class="center">{{ $r['reprogrammed']??0 }}</td><td class="center"><span class="badge {{ $bc }}">{{ $pct }}% · {{ $label }}</span></td></tr>@endforeach @if($agencies->isEmpty())<tr><td colspan="6" class="center">Sin datos.</td></tr>@endif</tbody></table></div>
<div class="sec"><div class="title">3 · Dirección / Unidad</div><table class="tbl"><thead><tr><th>Dirección / Unidad</th><th class="center">Entregables</th><th class="center">Validados</th><th class="center">Cumplimiento</th></tr></thead><tbody>@foreach($units as $r)<tr><td>{{ $r['unit']??'Sin unidad' }}</td><td class="center">{{ $r['total']??0 }}</td><td class="center">{{ $r['validated']??0 }}</td><td class="center">{{ $r['percentage']??0 }}%</td></tr>@endforeach @if($units->isEmpty())<tr><td colspan="4" class="center">Sin datos.</td></tr>@endif</tbody></table></div>
<div class="sec"><div class="title">4 · Tendencia mensual</div><table class="tbl"><thead><tr><th>Periodo</th><th class="center">Cargas</th><th class="center">Cerradas</th><th class="center">Cumplimiento</th></tr></thead><tbody>@foreach($monthly as $r)<tr><td>{{ $r['period']??'—' }}</td><td class="center">{{ $r['total']??0 }}</td><td class="center">{{ $r['closed']??0 }}</td><td class="center">{{ $r['compliance']??0 }}%</td></tr>@endforeach @if($monthly->isEmpty())<tr><td colspan="4" class="center">Sin información.</td></tr>@endif</tbody></table></div>
<div class="break"></div><h2>5 · Detalle por Dependencia</h2>@foreach($agencies as $r)<div class="group"><h3>DEPENDENCIA · {{ $r['agency']??'Sin dependencia' }}</h3><div class="gsub">{{ $r['total']??0 }} cargas · {{ $r['percentage']??0 }}% de cumplimiento</div><table class="tbl"><thead><tr><th>Indicador</th><th>Valor</th></tr></thead><tbody><tr><td>Validadas y cerradas</td><td>{{ $r['closed']??0 }}</td></tr><tr><td>Reprogramadas</td><td>{{ $r['reprogrammed']??0 }}</td></tr><tr><td>Vencidas</td><td>{{ $r['overdue']??0 }}</td></tr></tbody></table></div>@endforeach
<div class="foot">SIGET · Reporte generado conforme al alcance autorizado del usuario. Formato A4 horizontal para impresión y archivo.</div></body></html>
