<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<style>
@page{size:A4 landscape;margin:14mm 16mm}body{font-family:DejaVu Sans,sans-serif;font-size:8px;color:#243247;margin:0}h1,h2,h3,p{margin:0}.head{background:#10213b;color:#fff;padding:12px 14px;border-radius:5px;margin-bottom:8px}.head h1{font-size:18px;color:#fff}.head p{font-size:8px;color:#d8e1ec;margin-top:3px}.eyebrow{font-size:6px;letter-spacing:1px;text-transform:uppercase;color:#b9c8dc;margin-bottom:3px}.meta,.kpi,.tbl{width:100%;border-collapse:collapse}.meta{margin-top:8px}.meta td{border:1px solid #52637b;padding:5px;font-size:7px}.meta b{display:block;color:#b9c8dc;font-size:6px;text-transform:uppercase}.kpi{margin:0 0 8px}.kpi td{width:16.66%;border:1px solid #d6dde7;background:#f5f7fa;padding:6px;text-align:center}.kpi .lab{font-size:6px;color:#69778a;text-transform:uppercase}.kpi strong{font-size:14px;color:#10213b}.sec{border:1px solid #d8dee7;border-radius:4px;overflow:hidden;margin-bottom:8px}.title{background:#10213b;color:#fff;padding:6px 8px;font-size:8px;font-weight:bold}.sub{background:#f0f3f7;color:#5f6d80;padding:5px 8px;font-size:6.5px}.tbl{font-size:6.8px}.tbl th{background:#15263f;color:#fff;padding:5px;text-align:left;font-size:6px;text-transform:uppercase}.tbl td{padding:5px;border:1px solid #e0e5ec}.num{text-align:right}.badge{padding:2px 4px;border-radius:4px;font-size:5.5px;font-weight:bold}.ok{background:#e7f6ee;color:#127a49}.warn{background:#fff4d7;color:#966700}.danger{background:#fdeaea;color:#a82d2d}.total{background:#eef2f6;font-weight:bold}.foot{margin-top:8px;border-top:1px solid #d7dee8;padding-top:5px;color:#758194;font-size:6px}.group{page-break-inside:avoid;margin-bottom:8px}.group h3{background:#e9eef4;color:#10213b;padding:6px 8px;font-size:8px}.group .gsub{background:#f7f9fb;padding:5px 8px;border-top:1px solid #dbe1e9;border-bottom:1px solid #dbe1e9;font-size:6.5px;font-weight:bold}
</style>
</head>
<body>
@php
$summary=$evidenceSummary??[];$rows=collect($reportRows??[]);$grouped=$rows->groupBy('agency');
@endphp
<div class="head"><div class="eyebrow">SIGET · Reporte ejecutivo institucional · Formato A4 horizontal</div><h1>Reporte de cumplimiento de evidencias</h1><p>Resumen ejecutivo y desglose agrupado por dependencia, dirección, unidad y carga.</p><table class="meta"><tr><td><b>Periodo</b>{{ ($filters['from']??null)?:'Universo actual' }} @if(!empty($filters['to'])) → {{ $filters['to'] }} @endif</td><td><b>Generado por</b>{{ $generatedBy->name }}</td><td><b>Emisión</b>{{ now()->format('d/m/Y H:i') }}</td><td><b>Cargas</b>{{ number_format($rows->count()) }}</td></tr></table></div>
<table class="kpi"><tr><td><div class="lab">Esperadas</div><strong>{{ number_format($summary['expected']??0) }}</strong></td><td><div class="lab">Recibidas</div><strong>{{ number_format($summary['received']??0) }}</strong></td><td><div class="lab">Validadas</div><strong>{{ number_format($summary['validated']??0) }}</strong></td><td><div class="lab">Pendientes</div><strong>{{ number_format($summary['pending']??0) }}</strong></td><td><div class="lab">Observadas</div><strong>{{ number_format($summary['observed']??0) }}</strong></td><td><div class="lab">Cumplimiento entrega</div><strong>{{ number_format($summary['delivery_percentage']??0,1) }}%</strong></td></tr></table>
<div class="sec"><div class="title">1 · Resumen institucional</div><div class="sub">La entrega mide evidencias recibidas frente a evidencias esperadas. La validación se presenta por separado.</div><table class="tbl"><thead><tr><th>Indicador</th><th class="num">Esperadas</th><th class="num">Recibidas</th><th class="num">Validadas</th><th class="num">Pendientes</th><th class="num">Observadas</th><th class="num">Entrega</th><th class="num">Validación</th></tr></thead><tbody><tr class="total"><td>Total institucional</td><td class="num">{{ number_format($summary['expected']??0) }}</td><td class="num">{{ number_format($summary['received']??0) }}</td><td class="num">{{ number_format($summary['validated']??0) }}</td><td class="num">{{ number_format($summary['pending']??0) }}</td><td class="num">{{ number_format($summary['observed']??0) }}</td><td class="num">{{ number_format($summary['delivery_percentage']??0,1) }}%</td><td class="num">{{ number_format($summary['validation_percentage']??0,1) }}%</td></tr></tbody></table></div>
<div class="sec"><div class="title">2 · Detalle por dependencia y carga</div><table class="tbl"><thead><tr><th>Dependencia</th><th>Dirección / Unidad</th><th>Campaña / carga</th><th>Estado</th><th class="num">Esperadas</th><th class="num">Recibidas</th><th class="num">Validadas</th><th class="num">Pendientes</th><th class="num">Observadas</th><th class="num">Cumplimiento</th><th>Riesgo</th></tr></thead><tbody>@forelse($rows as $r)<tr><td>{{ $r['agency'] }}</td><td>{{ $r['unit'] }}</td><td>{{ $r['title'] }}</td><td>{{ $r['status'] }}</td><td class="num">{{ $r['expected'] }}</td><td class="num">{{ $r['received'] }}</td><td class="num">{{ $r['validated'] }}</td><td class="num">{{ $r['pending'] }}</td><td class="num">{{ $r['observed'] }}</td><td class="num">{{ $r['expected'] ? number_format($r['received']*100/$r['expected'],1) : '0.0' }}%</td><td><span class="badge {{ $r['risk']==='ALTO'?'danger':($r['risk']==='NORMAL'?'ok':'warn') }}">{{ $r['risk'] }}</span></td></tr>@empty<tr><td colspan="11">Sin registros para el filtro seleccionado.</td></tr>@endforelse</tbody></table></div>
<div class="sec"><div class="title">3 · Totales por dependencia</div><table class="tbl"><thead><tr><th>Dependencia</th><th class="num">Cargas</th><th class="num">Esperadas</th><th class="num">Recibidas</th><th class="num">Validadas</th><th class="num">Pendientes</th><th class="num">Cumplimiento</th></tr></thead><tbody>@foreach($grouped as $agency=>$items)@php $e=$items->sum('expected');$r=$items->sum('received');$v=$items->sum('validated');$p=$items->sum('pending');@endphp<tr><td><strong>{{ $agency }}</strong></td><td class="num">{{ $items->count() }}</td><td class="num">{{ $e }}</td><td class="num">{{ $r }}</td><td class="num">{{ $v }}</td><td class="num">{{ $p }}</td><td class="num">{{ $e ? number_format($r*100/$e,1) : '0.0' }}%</td></tr>@endforeach</tbody></table></div>
<div class="foot">SIGET · Reporte generado conforme al alcance autorizado del usuario. “Formato tipo Crystal Reports”: salida paginada con encabezados, agrupaciones, subtotales y total general.</div>
</body></html>
