@extends('layouts.app')
@section('title','Centro de Reportes SIGET')
@section('page-title','Centro de Reportes SIGET')
@section('page-subtitle','Reportes ejecutivos, seguimiento y auditoría')
@section('content')
@php
$k=$analytics['kpis']??[];
$agencyRows=collect($analytics['agency_performance']??[]);
$directionRows=collect($analytics['direction_performance']??[]);
$monthlyRows=collect($analytics['monthly_trend']??[]);
$loadsByAgency=$loads->groupBy(fn($l)=>$l->agency?->name?:'Sin dependencia');
$statuses=['PROGRAMADA'=>'PROGRAMADO','REPROGRAMADA'=>'REPROGRAMADO','VALIDADO_Y_CERRADO'=>'VALIDADO Y CERRADO','VENCIDA'=>'VENCIDO'];
$scls=['PROGRAMADA'=>'info','REPROGRAMADA'=>'warn','VALIDADO_Y_CERRADO'=>'ok','VENCIDA'=>'danger'];
$dl=[];$dv=[];foreach($directionRows as $r){$dl[]=$r['unit']??'Sin unidad';$dv[]=(float)($r['percentage']??0);}
$ml=[];$mc=[];foreach($monthlyRows as $r){$ml[]=$r['period']??'';$mc[]=(float)($r['compliance']??0);}
@endphp
<style>
.siget-report-shell{background:var(--bg);color:var(--text);min-height:100%}.crbox,.crk{background:var(--surface);color:var(--text);border:1px solid var(--border);border-radius:12px}.crtop{padding:18px 20px;margin-bottom:15px;border-radius:12px;background:linear-gradient(135deg,var(--side),#203c63);color:#fff}.crtop h2{margin:0;color:#fff}.crtop p{margin:3px 0 0;color:#d4dfec;font-size:.75rem}.toolbar{padding:14px;margin-bottom:15px}.tabs{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:15px}.tab{padding:8px 11px;border:1px solid var(--border);border-radius:9px;background:var(--surface);color:var(--text);font-weight:700;font-size:.7rem;cursor:pointer}.tab.on{background:var(--primary);color:#fff}.panel{display:none}.panel.on{display:block}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin-bottom:15px}.crk{padding:11px}.crk small{display:block;color:var(--muted);font-size:.6rem;text-transform:uppercase}.crk strong{font-size:1.3rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.head{padding:12px 14px;background:var(--surface2);border-bottom:1px solid var(--border)}.head h3{margin:0;font-size:.9rem;color:var(--text)}.chart{height:260px;padding:10px}.stat{margin:8px;padding:8px;border:1px solid var(--border);border-left:4px solid var(--primary);border-radius:7px;background:var(--surface)}.stat.ok{border-left-color:var(--green)}.stat.warn{border-left-color:var(--amber)}.stat.danger{border-left-color:var(--red)}.band{padding:8px 11px;background:var(--side);color:#fff;font-weight:800;font-size:.7rem}.tbl{width:100%;border-collapse:collapse;font-size:.68rem;color:var(--text)}.tbl th{background:var(--side);color:#fff;padding:7px;text-align:left;font-size:.58rem}.tbl td{padding:7px;border-bottom:1px solid var(--border)}.tbl tr:nth-child(even) td{background:var(--surface2)}.builder-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:15px;padding:15px}.builder-field{padding:12px;border:1px solid var(--border);border-radius:10px;background:var(--surface2);margin-bottom:10px}.builder-field label{display:block;font-weight:800;font-size:.68rem;margin-bottom:5px}.builder-checks{display:grid;grid-template-columns:1fr 1fr;gap:7px}.builder-check{display:flex;gap:7px;align-items:center;padding:7px 8px;border:1px solid var(--border);border-radius:8px;background:var(--surface)}.builder-check label{margin:0;font-weight:600;font-size:.65rem}.builder-preview{min-height:260px;border:1px dashed var(--border);border-radius:10px;background:var(--surface2);padding:12px}.builder-actions{display:flex;gap:8px;flex-wrap:wrap}.builder-help{font-size:.66rem;color:var(--muted);margin-top:4px}@media(max-width:1000px){.kpis{grid-template-columns:repeat(3,1fr)}.grid,.builder-grid{grid-template-columns:1fr}}@media(max-width:600px){.kpis{grid-template-columns:repeat(2,1fr)}.builder-checks{grid-template-columns:1fr}}
html[data-bs-theme=dark] .crbox,html[data-bs-theme=dark] .crk,html[data-bs-theme=dark] .stat{box-shadow:0 2px 12px rgba(0,0,0,.22)}
</style>
<div class="siget-report-shell">
<div class="crtop"><div style="font-size:.62rem;text-transform:uppercase;letter-spacing:.08em;opacity:.75">SIGET · Centro de Reportes · Crystal</div><h2>Reportes Ejecutivos y de Auditoría</h2><p>Dependencia → Dirección / Unidad → Orden / Pauta.</p></div>
<form method="GET" action="{{ route('reports.index') }}" class="crbox toolbar"><div class="row g-3 align-items-end"><div class="col-lg-2"><label>Dependencia</label><select name="agency_id" class="form-select form-select-sm"><option value="">Todas</option>@foreach($agencies as $a)<option value="{{ $a->id }}">{{ $a->name }}</option>@endforeach</select></div><div class="col-lg-3"><label>Dirección / Unidad</label><select name="organizational_unit_id" class="form-select form-select-sm"><option value="">Todas</option>@foreach($units as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div><div class="col-lg-2"><label>Estado</label><select name="status" class="form-select form-select-sm"><option value="">Todos</option>@foreach($statuses as $c=>$l)<option value="{{ $c }}">{{ $l }}</option>@endforeach</select></div><div class="col-lg-2"><label>Desde</label><input type="month" name="from" value="{{ $filters['from']??'' }}" class="form-control form-control-sm"></div><div class="col-lg-2"><label>Hasta</label><input type="month" name="to" value="{{ $filters['to']??'' }}" class="form-control form-control-sm"></div><div class="col-lg-1"><button class="btn btn-primary btn-sm w-100">Aplicar</button></div></div></form>
<div class="tabs"><button class="tab on" data-r="exec">Ejecutivo</button><button class="tab" data-r="comp">Cumplimiento</button><button class="tab" data-r="deps">Dependencias</button><button class="tab" data-r="track">Seguimiento</button><button class="tab" data-r="audit">Auditoría</button>@if($canBuildReports)<button class="tab" data-r="build">Constructor</button>@endif @if($canExport)<a class="btn btn-danger btn-sm ms-auto" href="{{ route('reports.pdf',request()->query()) }}">PDF Crystal</a><a class="btn btn-success btn-sm" href="{{ route('reports.xlsx',request()->query()) }}">Excel</a>@endif</div>
<section id="exec" class="panel on"><div class="kpis"><div class="crk"><small>Total</small><strong>{{ number_format((int)($k['total']??0)) }}</strong></div><div class="crk"><small>Activas</small><strong>{{ number_format((int)($k['active']??0)) }}</strong></div><div class="crk ok"><small>Cerradas</small><strong>{{ number_format((int)($k['closed']??0)) }}</strong></div><div class="crk danger"><small>Vencidas</small><strong>{{ number_format((int)($k['overdue']??0)) }}</strong></div><div class="crk warn"><small>Reprogramadas</small><strong>{{ number_format((int)($k['reprogrammed']??0)) }}</strong></div><div class="crk"><small>Cumplimiento</small><strong>{{ number_format((float)($k['compliance']??0),1) }}%</strong></div></div><div class="grid"><div class="crbox"><div class="head"><h3>Avance por Dirección / Unidad</h3></div><div class="chart"><canvas id="sigetReportDirection"></canvas></div></div><div class="crbox"><div class="head"><h3>Tendencia de cumplimiento mensual</h3></div><div class="chart"><canvas id="sigetReportTrend"></canvas></div></div></div><div class="crbox" style="margin-top:15px"><div class="head"><h3>Resumen por dependencia</h3></div>@foreach($loadsByAgency as $agency=>$items)<div class="band">{{ $agency }} · {{ $items->count() }} cargas</div><table class="tbl"><thead><tr><th>Orden</th><th>Pauta</th><th>Estado</th><th>Avance</th></tr></thead><tbody>@foreach($items as $load)@php $code=$load->status instanceof \BackedEnum?$load->status->value:(string)$load->status;@endphp<tr><td>{{ $load->title }}</td><td>{{ $load->period_label?:'—' }}</td><td>{{ $statuses[$code]??$code }}</td><td>{{ number_format((float)$load->completion_percentage,0) }}%</td></tr>@endforeach</tbody></table>@endforeach</div></section>
<section id="comp" class="panel"><div class="crbox"><div class="head"><h3>Cumplimiento y Desempeño</h3></div><table class="tbl"><thead><tr><th>Dependencia</th><th>Programado</th><th>Reprogramado</th><th>Validado y cerrado</th><th>Vencido</th></tr></thead><tbody>@foreach($agencies as $a)@php $r=$loads->filter(fn($l)=>$l->agency?->id===$a->id);@endphp<tr><td>{{ $a->name }}</td><td>{{ $r->where('status','PROGRAMADA')->count() }}</td><td>{{ $r->where('status','REPROGRAMADA')->count() }}</td><td>{{ $r->where('status','VALIDADO_Y_CERRADO')->count() }}</td><td>{{ $r->where('status','VENCIDA')->count() }}</td></tr>@endforeach</tbody></table></div></section>
<section id="deps" class="panel"><div class="crbox"><div class="head"><h3>Dependencias</h3></div><div class="chart"><canvas id="sigetReportUnits"></canvas></div><table class="tbl"><thead><tr><th>Dependencia</th><th>Cargas</th><th>Cerradas</th><th>Vencidas</th><th>Reprogramadas</th><th>Cumplimiento</th></tr></thead><tbody>@foreach($agencyRows as $r)<tr><td>{{ $r['agency']??'Sin dependencia' }}</td><td>{{ $r['total']??0 }}</td><td>{{ $r['closed']??0 }}</td><td>{{ $r['overdue']??0 }}</td><td>{{ $r['reprogrammed']??0 }}</td><td>{{ $r['percentage']??0 }}%</td></tr>@endforeach</tbody></table></div></section>
<section id="track" class="panel"><div class="crbox"><div class="head"><h3>Seguimiento</h3></div><table class="tbl"><thead><tr><th>Dependencia</th><th>Orden</th><th>Estado</th><th>Avance</th></tr></thead><tbody>@foreach($loads as $load)@php $code=$load->status instanceof \BackedEnum?$load->status->value:(string)$load->status;@endphp @if(in_array($code,['REPROGRAMADA','VENCIDA','PROGRAMADA'],true))<tr><td>{{ $load->agency?->name?:'Sin dependencia' }}</td><td>{{ $load->title }}</td><td>{{ $statuses[$code]??$code }}</td><td>{{ number_format((float)$load->completion_percentage,0) }}%</td></tr>@endif @endforeach</tbody></table></div></section>
<section id="audit" class="panel"><div class="crbox"><div class="head"><h3>Auditoría</h3></div>@foreach($loadsByAgency as $agency=>$items)<div class="band">Dependencia · {{ $agency }}</div><table class="tbl"><thead><tr><th>Orden</th><th>Pauta</th><th>Apertura</th><th>Entrega</th><th>Estado</th></tr></thead><tbody>@foreach($items as $load)@php $code=$load->status instanceof \BackedEnum?$load->status->value:(string)$load->status;@endphp<tr><td>{{ $load->title }}</td><td>{{ $load->period_label?:'—' }}</td><td>{{ $load->effective_open_at?->format('d/m/Y H:i')?:'—' }}</td><td>{{ $load->delivered_at?->format('d/m/Y H:i')?:'—' }}</td><td>{{ $statuses[$code]??$code }}</td></tr>@endforeach</tbody></table>@endforeach</div></section>
@if($canBuildReports)<section id="build" class="panel"><div class="crbox"><div class="head"><h3>Constructor de Reportes</h3><p>Diseña un reporte a partir del universo filtrado y genera una salida reutilizable.</p></div><div class="builder-grid"><div><div class="builder-field"><label>1. Tipo de reporte</label><select id="builderType" class="form-select form-select-sm"><option value="executive">Ejecutivo Crystal</option><option value="compliance">Cumplimiento por dependencia</option><option value="audit">Auditoría de cargas</option><option value="followup">Seguimiento de pendientes</option></select></div><div class="builder-field"><label>2. Agrupar por</label><select id="builderGroup" class="form-select form-select-sm"><option value="agency">Dependencia</option><option value="unit">Dirección / Unidad</option><option value="status">Estado</option><option value="period">Pauta / periodo</option></select></div><div class="builder-field"><label>3. Columnas del reporte</label><div class="builder-checks"><div class="builder-check"><input id="bcAgency" type="checkbox" checked><label for="bcAgency">Dependencia</label></div><div class="builder-check"><input id="bcUnit" type="checkbox" checked><label for="bcUnit">Dirección / Unidad</label></div><div class="builder-check"><input id="bcTitle" type="checkbox" checked><label for="bcTitle">Orden / carga</label></div><div class="builder-check"><input id="bcStatus" type="checkbox" checked><label for="bcStatus">Estado</label></div><div class="builder-check"><input id="bcProgress" type="checkbox" checked><label for="bcProgress">Avance</label></div><div class="builder-check"><input id="bcDates" type="checkbox"><label for="bcDates">Fechas</label></div><div class="builder-check"><input id="bcEvidence" type="checkbox"><label for="bcEvidence">Evidencias</label></div><div class="builder-check"><input id="bcRisk" type="checkbox"><label for="bcRisk">Riesgo</label></div></div></div><div class="builder-field"><label>4. Formato de salida</label><select id="builderFormat" class="form-select form-select-sm"><option value="view">Vista previa</option><option value="pdf">PDF Crystal</option><option value="xlsx">Excel</option><option value="csv">CSV</option></select><div class="builder-help">Los filtros de arriba se respetan al construir la salida.</div></div><div class="builder-actions"><button type="button" id="builderPreview" class="btn btn-primary btn-sm">Construir vista previa</button><button type="button" id="builderExport" class="btn btn-outline-secondary btn-sm">Abrir salida</button></div></div><div><div class="builder-preview" id="builderPreviewBox"><strong>Constructor listo.</strong><p class="builder-help">Selecciona tipo, agrupación y columnas. La vista previa se basa en las cargas que devuelve el filtro actual.</p></div></div></div></div></section>@endif
</div>
<script>document.querySelectorAll('[data-r]').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.getElementById(b.dataset.r).classList.add('on');window.dispatchEvent(new Event('resize'));}});</script>
@if($canBuildReports)<script>(function(){var box=document.getElementById('builderPreviewBox');var baseQuery=new URLSearchParams(window.location.search);var labels={PROGRAMADA:'PROGRAMADO',REPROGRAMADA:'REPROGRAMADO',VALIDADO_Y_CERRADO:'VALIDADO Y CERRADO',VENCIDA:'VENCIDO'};function esc(v){return String(v??'').replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#039;'}[c];});}function checked(id){return document.getElementById(id).checked;}function render(){var rows=@json($loads->map(function($l){$unit=$l->deliverables->map(fn($d)=>$d->organizationalUnit?->name)->filter()->unique()->implode(' / ');$e=$l->deliverables->flatMap->evidences;return ['agency'=>$l->agency?->name?:'Sin dependencia','unit'=>$unit?:'—','title'=>$l->title,'status'=>$l->status instanceof \BackedEnum?$l->status->value:(string)$l->status,'progress'=>(float)$l->completion_percentage,'open'=>$l->effective_open_at?->format('d/m/Y H:i')?:'—','close'=>$l->effective_close_at?->format('d/m/Y H:i')?:'—','evidence'=>$e->count(),'risk'=>method_exists($l,'riskLevel')?'—':'—'];})->values());var group=document.getElementById('builderGroup').value;var cols=[];if(checked('bcAgency'))cols.push(['agency','Dependencia']);if(checked('bcUnit'))cols.push(['unit','Dirección / Unidad']);if(checked('bcTitle'))cols.push(['title','Orden / carga']);if(checked('bcStatus'))cols.push(['status','Estado']);if(checked('bcProgress'))cols.push(['progress','Avance']);if(checked('bcDates')){cols.push(['open','Apertura']);cols.push(['close','Cierre']);}if(checked('bcEvidence'))cols.push(['evidence','Evidencias']);if(checked('bcRisk'))cols.push(['risk','Riesgo']);var map={};rows.forEach(function(r){var key=r[group]??'—';(map[key]??=[]).push(r);});var html='<div class="band">'+esc(document.getElementById('builderType').selectedOptions[0].text)+' · '+esc(document.getElementById('builderGroup').selectedOptions[0].text)+' · '+rows.length+' registros</div>';Object.keys(map).sort().forEach(function(key){html+='<div style="margin-top:10px;font-weight:800">'+esc(key)+'</div><div style="overflow:auto"><table class="tbl"><thead><tr>'+cols.map(function(c){return '<th>'+esc(c[1])+'</th>';}).join('')+'</tr></thead><tbody>'+map[key].map(function(r){return '<tr>'+cols.map(function(c){var v=r[c[0]];if(c[0]==='status')v=labels[v]??v;if(c[0]==='progress')v=Number(v).toFixed(0)+'%';return '<td>'+esc(v)+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>';});box.innerHTML=html||'<p>No hay registros para la combinación actual de filtros.</p>';}
document.getElementById('builderPreview').onclick=render;document.getElementById('builderExport').onclick=function(){var format=document.getElementById('builderFormat').value;if(format==='view'){render();return;}var map={pdf:'reports.pdf',xlsx:'reports.xlsx',csv:'reports.csv'};var url=new URL('{{ url('/reportes') }}/'+map[format],window.location.origin);baseQuery.forEach(function(v,k){if(v)url.searchParams.set(k,v);});window.open(url.toString(),'_blank');};})();</script>@endif
<script type="application/json" data-siget-chart="sigetReportDirection">{!! json_encode(['type'=>'bar','data'=>['labels'=>$dl,'datasets'=>[['label'=>'Avance realizado %','data'=>$dv]]],'options'=>['scales'=>['y'=>['beginAtZero'=>true,'max'=>100]]]]) !!}</script>
<script type="application/json" data-siget-chart="sigetReportTrend">{!! json_encode(['type'=>'line','data'=>['labels'=>$ml,'datasets'=>[['label'=>'Cumplimiento %','data'=>$mc,'fill'=>false]]],'options'=>['scales'=>['y'=>['beginAtZero'=>true,'max'=>100]]]]) !!}</script>
<script type="application/json" data-siget-chart="sigetReportUnits">{!! json_encode(['type'=>'bar','data'=>['labels'=>$dl,'datasets'=>[['label'=>'Avance realizado %','data'=>$dv]]],'options'=>['scales'=>['y'=>['beginAtZero'=>true,'max'=>100]]]]) !!}</script>
@endsection