DO $$ BEGIN
    CREATE TYPE user_status AS ENUM ('ACTIVE','INACTIVE','BLOCKED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE scheduled_load_status AS ENUM (
        'PROGRAMADA','ABIERTA','EN_CAPTURA','PARCIALMENTE_ENTREGADA',
        'ENTREGADA','EN_REVISION_INSTITUCIONAL','OBSERVADA',
        'LISTA_PARA_FIRMA','PENDIENTE_DOCUMENTO_FIRMADO',
        'VALIDADA','VALIDADO_Y_CERRADO','SUSPENDIDA',
        'REPROGRAMADA','REPROGRAMADA_ABIERTA','REPROGRAMADA_ENTREGADA',
        'VENCIDA','CANCELADA','REABIERTA'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE deliverable_status AS ENUM (
        'PENDIENTE','EN_CAPTURA','ENVIADO','EN_REVISION',
        'OBSERVADO','CORREGIDO','VALIDADO','CERRADO'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE import_status AS ENUM (
        'UPLOADED','VALIDATING','VALIDATED','WITH_ERRORS','CONFIRMED','CANCELLED'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE notification_channel AS ENUM ('IN_APP','EMAIL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE notification_status AS ENUM ('PENDING','QUEUED','SENT','FAILED','READ');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE traffic_light AS ENUM (
        'GRAY','BLUE','YELLOW','PURPLE','ORANGE','GREEN','DARK_GREEN','RED'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
