@extends('layouts.app')
@section('title','Centro de Inteligencia')
@section('page-title','Centro de Inteligencia Ejecutiva')
@section('page-subtitle','Lectura institucional para Dirección General: desempeño, capacidad, riesgo y tendencia. La operación detallada queda fuera de esta vista.')
@section('content')
@php
$k=$analytics['kpis']??[]; $filters=$filters??[]; $total=max((int)($k['total']??0),1); $closed=(int)($k['closed']??0); $overdue=(int)($k['overdue']??0); $reprogrammed=(int)($k['reprogrammed']??0); $active=(int)($k['active']??0); $riskRate=round(100*$overdue/$total,1); $closureRate=round(100*$closed/$total,1); $reprogramRate=round(100*$reprogrammed/$total,1); $activeRate=round(100*$active/$total,1); $trend=collect($analytics['monthly_trend']??[]); $directions=collect($analytics['direction_performance']??[])->take(10); $agencyRows=collect($analytics['agency_performance']??[])->take(10); $statusDistribution=collect($analytics['status_distribution']??[])->only(['REPROGRAMADA','VENCIDA','VALIDADO_Y_CERRADO']);
@endphp
<section class="siget-hero mb-4"><div class="d-flex justify-content-between align-items-start gap-3"><div><span class="badge text-bg-primary mb-2">Vista para Dirección General</span><h2>Centro de Inteligencia Ejecutiva</h2><p>La pregunta aquí no es qué registro está pendiente, sino <strong>dónde está el desempeño, dónde está la presión y cómo está evolucionando la operación</strong>.</p></div><div class="text-end"><small class="d-block text-muted">Universo analizado</small><strong class="fs-5">{{ number_format($k['total']??0) }} cargas</strong></div></div></section>
<form method="GET" class="card siget-card mb-4"><div class="card-header"><div><h2>Alcance ejecutivo</h2><p>Todos los indicadores se recalculan con el mismo universo de información.</p></div></div><div class="card-body row g-3 align-items-end"><div class="col-xl-3 col-md-6"><label class="form-label">Dependencia</label><select name="agency_id" class="form-select"><option value="">Todas las dependencias</option>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected(($filters['agency_id']??null)==$agency->id)>{{ $agency->name }}</option>@endforeach</select></div><div class="col-xl-3 col-md-6"><label class="form-label">Dirección / unidad</label><select name="organizational_unit_id" class="form-select"><option value="">Todas las direcciones / unidades</option>@foreach($units as $unit)@php $unitIdList=implode(',',array_map('strval',(array)($unit->filter_unit_ids??[$unit->id]))); @endphp<option value="{{ $unitIdList }}" @selected((string)($filters['organizational_unit_id']??'') === $unitIdList)>{{ $unit->name }}</option>@endforeach</select></div><div class="col-xl-2 col-md-4"><label class="form-label">Estado</label><select name="status" class="form-select"><option value="">Todos</option>@foreach(['REPROGRAMADA','VENCIDA','VALIDADO_Y_CERRADO'] as $status)<option value="{{ $status }}" @selected(($filters['status']??null)==$status)>{{ match($status){'REPROGRAMADA'=>'Reprogramada','VENCIDA'=>'Vencida','VALIDADO_Y_CERRADO'=>'Validado y cerrado',default=>$status} }}</option>@endforeach</select></div><div class="col-xl-2 col-md-4"><label class="form-label">Desde</label><input type="date" name="from" value="{{ $filters['from']??'' }}" class="form-control"></div><div class="col-xl-2 col-md-4"><label class="form-label">Hasta</label><input type="date" name="to" value="{{ $filters['to']??'' }}" class="form-control"></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Actualizar lectura</button><a href="{{ route('intelligence') }}" class="btn btn-outline-secondary">Restablecer</a><a href="{{ route('dashboard',request()->query()) }}" class="btn btn-outline-primary ms-auto">Dashboard ejecutivo</a></div></div></form>
<div class="row g-3 mb-4">@foreach([['Cumplimiento efectivo',$k['compliance']??0,'%','bi-check2-circle','success','Cierres validados sobre el universo'],['Avance medio',$k['completion_average']??0,'%','bi-speedometer2','primary','Avance promedio reportado'],['Presión de riesgo',$riskRate,'%','bi-exclamation-triangle','danger','Peso de cargas vencidas'],['Presión operativa',$activeRate,'%','bi-activity','info','Cargas actualmente en operación'],['Reprogramación',$reprogramRate,'%','bi-arrow-repeat','warning','Peso de cargas reprogramadas'],['Cierre efectivo',$closureRate,'%','bi-patch-check','success','Cargas que llegaron a cierre']] as [$label,$value,$suffix,$icon,$type,$hint])<div class="col-6 col-xl-2"><div class="siget-kpi h-100"><div class="siget-kpi-icon text-bg-{{ $type }}"><i class="bi {{ $icon }}"></i></div><div><small>{{ $label }}</small><strong>{{ $value }}{{ $suffix }}</strong><span class="d-block small text-muted mt-1">{{ $hint }}</span></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-8"><div class="card siget-card h-100"><div class="card-header"><div><h2>Tendencia institucional</h2><p>¿La capacidad de cierre acompaña el volumen de trabajo?</p></div></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="executiveTrendChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><div><h2>Composición de la operación</h2><p>Estados relevantes para la lectura ejecutiva.</p></div></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="executiveStatusChart"></canvas></div></div></div></div><div class="col-xl-7"><div class="card siget-card h-100"><div class="card-header"><div><h2>Desempeño comparativo por Dirección</h2><p>Volumen, cierre y vencimiento para identificar brechas de gestión.</p></div></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="executiveDirectionChart"></canvas></div></div></div></div><div class="col-xl-5"><div class="card siget-card h-100"><div class="card-header"><div><h2>Concentración de riesgo por Dependencia</h2><p>La prioridad ejecutiva es la concentración, no el detalle de cada registro.</p></div></div><div class="card-body"><div class="siget-chart-wrap"><canvas id="executiveRiskChart"></canvas></div></div></div></div></div>
<div class="row g-4 mt-1"><div class="col-xl-8"><div class="card siget-card"><div class="card-header"><div><h2>Matriz ejecutiva de desempeño</h2><p>Mayor avance y menor riesgo representan mejor posición.</p></div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Dirección</th><th>Cargas</th><th>Cierre</th><th>Vencidas</th><th>Lectura</th></tr></thead><tbody>@forelse($directions as $row)@php $pct=(float)($row['percentage']??0); $od=(int)($row['overdue']??0); $reading=$od>0?'Atención prioritaria':($pct>=80?'Desempeño favorable':'Seguimiento'); @endphp<tr><td><strong>{{ $row['unit'] }}</strong></td><td>{{ $row['total'] }}</td><td>{{ $pct }}%</td><td>{{ $od }}</td><td><span class="badge {{ $od>0?'text-bg-warning':($pct>=80?'text-bg-success':'text-bg-secondary') }}">{{ $reading }}</span></td></tr>@empty<tr><td colspan="5" class="text-center py-4">Sin información para comparar.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-xl-4"><div class="card siget-card h-100"><div class="card-header"><div><h2>Lectura para Dirección General</h2><p>Indicadores que orientan la decisión.</p></div></div><div class="card-body"><div class="vstack gap-3"><div><small class="text-muted">1 · Desempeño</small><strong class="d-block">{{ $k['compliance']??0 }}% de cumplimiento</strong></div><div><small class="text-muted">2 · Capacidad</small><strong class="d-block">{{ $k['active']??0 }} cargas en operación</strong></div><div><small class="text-muted">3 · Riesgo</small><strong class="d-block">{{ $k['overdue']??0 }} cargas vencidas</strong></div><div><small class="text-muted">4 · Estabilidad</small><strong class="d-block">{{ $k['reprogrammed']??0 }} cargas reprogramadas</strong></div><div><small class="text-muted">5 · Oportunidad</small><strong class="d-block">{{ $k['due_soon']??0 }} con vencimiento en 72 h</strong></div></div></div></div></div></div>
<script type="application/json" data-siget-chart="executiveTrendChart">{!! json_encode(['type'=>'line','labels'=>$trend->pluck('period')->values(),'datasets'=>[['label'=>'Entradas','data'=>$trend->pluck('total')->values()],['label'=>'Cierres','data'=>$trend->pluck('closed')->values()],['label'=>'Cumplimiento %','data'=>$trend->pluck('compliance')->values(),'yAxisID'=>'y1']]]) !!}</script>
<script type="application/json" data-siget-chart="executiveStatusChart">{!! json_encode(['type'=>'doughnut','labels'=>['Reprogramadas','Vencidas','Validadas y cerradas'],'datasets'=>[['label'=>'Cargas','data'=>[$statusDistribution->get('REPROGRAMADA',0),$statusDistribution->get('VENCIDA',0),$statusDistribution->get('VALIDADO_Y_CERRADO',0)]]]]) !!}</script>
<script type="application/json" data-siget-chart="executiveDirectionChart">{!! json_encode(['type'=>'bar','labels'=>$directions->pluck('unit')->values(),'datasets'=>[['label'=>'Cierre %','data'=>$directions->pluck('percentage')->values()],['label'=>'Vencidas','data'=>$directions->pluck('overdue')->values()] ]]) !!}</script>
<script type="application/json" data-siget-chart="executiveRiskChart">{!! json_encode(['type'=>'bar','labels'=>$agencyRows->pluck('agency')->values(),'datasets'=>[['label'=>'Vencidas','data'=>$agencyRows->pluck('overdue')->values()],['label'=>'Cumplimiento %','data'=>$agencyRows->pluck('percentage')->values()] ]]) !!}</script>
@endsection
