@extends('layouts.app')
@section('title','Calendario')
@section('page-title','Calendario inteligente de pautas')
@section('page-subtitle','Fechas habilitadas automáticamente a partir de las marcas X de las pautas confirmadas.')
@section('content')
<div class="siget-calendar-layout">
<div class="card siget-card"><div class="card-header flex-wrap"><div><h2>Programación institucional</h2><p>Seleccione una dependencia para filtrar eventos y ventanas de carga.</p></div><select id="calendarAgency" class="form-select" style="max-width:280px"><option value="">Alcance de mi usuario</option>@foreach($agencies as $a)<option value="{{ $a->id }}">{{ $a->name }}</option>@endforeach</select></div><div class="card-body"><div class="d-flex flex-wrap gap-3 mb-3 small text-secondary"><span><i class="bi bi-circle-fill text-primary me-1"></i>Programada</span><span><i class="bi bi-circle-fill text-success me-1"></i>Validada y cerrada</span><span><i class="bi bi-circle-fill text-warning me-1"></i>Próxima a vencer</span><span><i class="bi bi-circle-fill text-danger me-1"></i>Vencida u observada</span></div><div id="sigetCalendar" data-events-url="{{ route('calendar.events') }}" data-programmed-url="{{ route('calendar.programmed-dates') }}"></div></div></div>
<aside><div class="card siget-card mb-4"><div class="card-header"><div><h2>Próximos eventos</h2><p>Aperturas y fechas límite dentro de su alcance.</p></div></div><div class="card-body"><div class="siget-upcoming-list">@forelse($upcoming as $load)@php($traffic=$load->traffic_light instanceof \BackedEnum?$load->traffic_light->value:$load->traffic_light)<a href="{{ route('loads.show',$load) }}" class="siget-upcoming-event"><span class="siget-event-bar" style="background:{{ match(strtoupper((string)$traffic)){ 'RED'=>'#d64550','YELLOW'=>'#f59e0b','GREEN'=>'#22a06b',default=>'#0db8c9'} }}"></span><span><strong>{{ $load->title }}</strong><small>{{ $load->agency?->name }}</small><small><i class="bi bi-clock me-1"></i>{{ $load->effective_close_at?->format('d/m/Y H:i') }} · {{ $load->completion_percentage }}%</small></span></a>@empty<p class="text-secondary small">No existen eventos próximos.</p>@endforelse</div></div></div>
@if($canImport)<div class="card siget-card"><div class="card-header"><div><h2>Importar pauta</h2><p>Excel horizontal con meses, días y marcas X.</p></div></div><div class="card-body"><form method="POST" action="{{ route('calendar.import.store') }}" enctype="multipart/form-data">@csrf<div class="mb-3"><label class="form-label">Dependencia</label><select name="contracting_agency_id" class="form-select" required>@foreach($agencies as $a)<option value="{{ $a->id }}">{{ $a->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Año</label><input name="schedule_year" type="number" min="2020" max="2100" value="{{ now()->year }}" class="form-control" required></div><div class="mb-3"><label class="form-label">Archivo Excel</label><input name="calendar_file" type="file" accept=".xlsx,.xls" class="form-control" required></div><button class="btn btn-primary w-100"><i class="bi bi-file-earmark-spreadsheet me-1"></i>Validar pauta</button></form><a href="{{ asset('samples/Pauta_Bienestar_QA.xlsx') }}" class="btn btn-outline-secondary w-100 mt-2" download>Descargar muestra</a></div></div>@endif
</aside></div>
@endsection
