<?php

namespace App\Enums;

enum ScheduledLoadStatus: string
{
    case PROGRAMADA = 'PROGRAMADA';
    case ABIERTA = 'ABIERTA';
    case EN_CAPTURA = 'EN_CAPTURA';
    case PARCIALMENTE_ENTREGADA = 'PARCIALMENTE_ENTREGADA';
    case ENTREGADA = 'ENTREGADA';
    case EN_REVISION_INSTITUCIONAL = 'EN_REVISION_INSTITUCIONAL';
    case OBSERVADA = 'OBSERVADA';
    case LISTA_PARA_FIRMA = 'LISTA_PARA_FIRMA';
    case PENDIENTE_DOCUMENTO_FIRMADO = 'PENDIENTE_DOCUMENTO_FIRMADO';
    case VALIDADA = 'VALIDADA';
    case VALIDADO_Y_CERRADO = 'VALIDADO_Y_CERRADO';
    case SUSPENDIDA = 'SUSPENDIDA';
    case REPROGRAMADA = 'REPROGRAMADA';
    case REPROGRAMADA_ABIERTA = 'REPROGRAMADA_ABIERTA';
    case REPROGRAMADA_ENTREGADA = 'REPROGRAMADA_ENTREGADA';
    case VENCIDA = 'VENCIDA';
    case CANCELADA = 'CANCELADA';
    case REABIERTA = 'REABIERTA';
}
