<!doctype html><html lang="es" data-siget-theme="auto"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="color-scheme" content="light dark"><title>@yield('title',config('siget.name')) · {{ config('siget.subtitle') }}</title>
<script>(()=>{const d=document.documentElement;const zenithVersion='zenith-2026-10-09-readable-v2';if(localStorage.getItem('zenith-visual-version')!==zenithVersion){localStorage.setItem('zenith-preset','default');localStorage.setItem('zenith-visual-version',zenithVersion)}const t=localStorage.getItem('siget-theme')||@json(config('siget.default_theme','auto'));const r=t==='auto'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):t;d.dataset.sigetTheme=t;d.dataset.bsTheme=r;d.dataset.zenithPreset=localStorage.getItem('zenith-preset')||'default';d.dataset.zenithDensity=localStorage.getItem('zenith-density')||'default';d.dataset.zenithContainer=localStorage.getItem('zenith-container')||'fluid';d.dataset.zenithRadius=localStorage.getItem('zenith-radius')||'default';})();</script>
@php $mPath=public_path('build/manifest.json');$m=file_exists($mPath)?json_decode(file_get_contents($mPath),true):[];$css=$m['resources/css/app.scss']['file']??null;$js=$m['resources/js/app.js']['file']??null;$u=auth()->user();$role=$u?->role?->code??'';$isAdmin=$role==='ADMINISTRADOR';$canAlerts=$u?->hasPermission('alerts.view')??false;$menu=\App\Support\RoleMenu::for($role);$unread=$canAlerts?\App\Models\NotificationRecord::query()->where('user_id',auth()->id())->whereNull('read_at')->count():0;$latest=$canAlerts?\App\Models\NotificationRecord::query()->where('user_id',auth()->id())->latest()->limit(5)->get():collect(); @endphp
@if($css)<link rel="stylesheet" href="{{ '/build/'.ltrim($css,'/') }}">@endif @if($js)<script type="module" src="{{ '/build/'.ltrim($js,'/') }}"></script>@endif
<link rel="stylesheet" href="{{ asset('siget-zenith-runtime.css') }}?v={{ @filemtime(public_path('siget-zenith-runtime.css')) ?: '1' }}">
<script defer src="{{ asset('siget-zenith-runtime.js') }}?v={{ @filemtime(public_path('siget-zenith-runtime.js')) ?: '1' }}"></script>
<script defer src="{{ asset('report-executive-fallback.js') }}"></script></head>
<body class="siget-body siget-zenith" data-siget-ui="zenith"><div class="siget-shell"><aside class="siget-sidebar"><div class="siget-sidebar-head"><a href="{{ route('dashboard') }}" class="siget-brand"><img class="siget-brand-seal" src="{{ asset('images/siget-seal-clean.png') }}" alt="Escudo de México"><span class="siget-brand-copy"><strong>{{ config('siget.name') }}</strong><small>{{ config('siget.subtitle') }}</small></span></a><button class="siget-icon-button d-lg-none" data-siget-sidebar-close><i class="bi bi-x-lg"></i></button></div>
<div class="siget-user-card"><div class="siget-avatar">{{ strtoupper(mb_substr($u?->name??'U',0,1)) }}</div><div class="min-w-0"><strong>{{ $u?->name }}</strong><small>{{ $u?->role?->name }}</small><small>{{ $u?->organizationalUnit?->name ?: $u?->agency?->name }}</small></div></div>
<nav class="siget-nav">@foreach($menu as $item) @if(Route::has($item['route']))<a href="{{ route($item['route']) }}" class="{{ request()->routeIs($item['route'])?'active':'' }}"><i class="bi {{ $item['icon'] }}"></i><span>{{ $item['label'] }}</span></a>@endif @endforeach</nav>
<div class="siget-sidebar-footer"><div class="siget-sidebar-government"><img src="{{ asset('images/mexico-seal-clean.png') }}" alt="Escudo nacional"><div><strong>Gobierno de México</strong><small>Gobierno de la República</small></div></div><div class="siget-sidebar-system"><span class="siget-status-dot"></span><div><strong>Ambiente activo</strong><small>{{ config('siget.environment_label') }}</small></div></div>@if(config('siget.mailpit_url'))<a href="{{ config('siget.mailpit_url') }}" target="_blank" class="siget-sidebar-link"><i class="bi bi-envelope-paper"></i> Correo QA Mailpit</a>@endif @if($isAdmin&&Route::has('qa.credentials'))<a href="{{ route('qa.credentials') }}" class="siget-sidebar-link"><i class="bi bi-key"></i> Credenciales QA</a>@endif<form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-outline-light btn-sm w-100"><i class="bi bi-box-arrow-right"></i> Cerrar sesión</button></form></div></aside><div class="siget-sidebar-backdrop" data-siget-sidebar-close></div>
<main class="siget-main"><header class="siget-topbar"><div class="siget-topbar-left"><button class="siget-icon-button" data-siget-sidebar-toggle><i class="bi bi-list"></i></button><div><p class="siget-eyebrow">{{ config('siget.name') }} · {{ config('siget.subtitle') }}</p><h1>@yield('page-title',config('siget.name'))</h1>@hasSection('page-subtitle')<p class="siget-page-subtitle">@yield('page-subtitle')</p>@endif</div></div>
<div class="siget-top-actions"><form action="{{ route('repository.index') }}" method="GET" class="siget-global-search d-none d-xl-flex"><i class="bi bi-search"></i><input name="q" placeholder="Buscar carga o dependencia"></form><div class="dropdown"><button class="siget-icon-button" data-bs-toggle="dropdown"><i class="bi bi-circle-half" data-theme-icon></i></button><div class="dropdown-menu dropdown-menu-end"><button class="dropdown-item" data-theme-value="light"><i class="bi bi-sun me-2"></i>Claro</button><button class="dropdown-item" data-theme-value="dark"><i class="bi bi-moon-stars me-2"></i>Oscuro</button><button class="dropdown-item" data-theme-value="auto"><i class="bi bi-circle-half me-2"></i>Automático</button></div></div><button class="siget-icon-button" type="button" aria-label="Personalizar apariencia" data-zenith-customizer-toggle><i class="bi bi-palette2"></i></button>
@if($canAlerts)<div class="dropdown"><button class="siget-icon-button position-relative" data-bs-toggle="dropdown"><i class="bi bi-bell"></i>@if($unread)<span class="siget-notification-count">{{ $unread>99?'99+':$unread }}</span>@endif</button><div class="dropdown-menu dropdown-menu-end siget-notification-dropdown"><div class="siget-dropdown-heading"><strong>Notificaciones</strong><span>{{ $unread }} sin leer</span></div>@forelse($latest as $n)<a href="{{ $n->action_url?:route('alerts.index') }}" class="siget-mini-notification {{ $n->read_at?'':'is-unread' }}"><span class="siget-notification-icon"><i class="bi bi-bell"></i></span><span><strong>{{ $n->subject }}</strong><small>{{ \Illuminate\Support\Str::limit($n->message,80) }}</small></span></a>@empty<div class="siget-empty-mini">No hay notificaciones.</div>@endforelse<a href="{{ route('alerts.index') }}" class="siget-dropdown-footer">Ver centro de notificaciones</a></div></div>@endif<span class="siget-env-badge">{{ config('siget.environment_label') }}</span><div class="siget-top-user d-none d-md-flex"><span class="siget-avatar siget-avatar-sm">{{ strtoupper(mb_substr($u?->name??'U',0,1)) }}</span><span><strong>{{ $u?->name }}</strong><small>{{ $u?->role?->name }}</small></span></div></div></header>
<section class="siget-content">@if(session('status'))<div class="alert alert-info alert-dismissible fade show">{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif @if(session('success'))<div class="alert alert-success alert-dismissible fade show">{{ session('success') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif @if(session('error'))<div class="alert alert-warning alert-dismissible fade show"><strong>{{ str_contains(session('error'), 'Archivo no permitido') ? 'Archivo no permitido' : 'No se pudo procesar la evidencia' }}:</strong> {{ session('error') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif @if($errors->any())<div class="alert alert-danger"><strong>Revise la información:</strong><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif @yield('content')</section></main></div><div class="siget-customizer" data-zenith-customizer aria-hidden="true">
  <div class="siget-customizer-backdrop" data-zenith-customizer-close></div>
  <aside class="siget-customizer-panel" role="dialog" aria-modal="true" aria-label="Personalizar apariencia">
    <div class="siget-customizer-head"><div><strong>Personalizar apariencia</strong><small>Zenith · sistema visual SIGET</small></div><button class="siget-icon-button" type="button" data-zenith-customizer-close aria-label="Cerrar"><i class="bi bi-x-lg"></i></button></div>
    <div class="siget-customizer-body">
      <section class="siget-customizer-section"><h3>Color</h3><p>Color global para botones, estados activos, foco e indicadores.</p>
        <div class="siget-preset-grid">
          <button type="button" class="siget-preset" data-zenith-preset="default"><span></span><strong>Default</strong><small>Teal</small></button>
          <button type="button" class="siget-preset" data-zenith-preset="ocean"><span></span><strong>Ocean</strong><small>Blue</small></button>
          <button type="button" class="siget-preset" data-zenith-preset="sunset"><span></span><strong>Sunset</strong><small>Warm</small></button>
          <button type="button" class="siget-preset" data-zenith-preset="forest"><span></span><strong>Forest</strong><small>Green</small></button>
          <button type="button" class="siget-preset" data-zenith-preset="berry"><span></span><strong>Berry</strong><small>Violet</small></button>
          <button type="button" class="siget-preset" data-zenith-preset="slate"><span></span><strong>Slate</strong><small>Neutral</small></button>
        </div></section>
      <section class="siget-customizer-section"><h3>Densidad</h3><p>Escala tipográfica y espacio general.</p>
        <div class="siget-choice-row three"><button type="button" data-zenith-density="compact">Compacta</button><button type="button" data-zenith-density="default">Predeterminada</button><button type="button" data-zenith-density="comfortable">Cómoda</button></div></section>
      <section class="siget-customizer-section"><h3>Contenedor</h3><p>Ancho completo o contenido centrado.</p>
        <div class="siget-choice-row two"><button type="button" data-zenith-container="fluid">Fluido</button><button type="button" data-zenith-container="boxed">Encajonado</button></div></section>
      <section class="siget-customizer-section"><h3>Radio</h3><p>Redondeado de tarjetas, botones y controles.</p>
        <div class="siget-choice-row three"><button type="button" data-zenith-radius="compact">Compacto</button><button type="button" data-zenith-radius="default">Default</button><button type="button" data-zenith-radius="soft">Suave</button></div></section>
      <section class="siget-customizer-section"><h3>Tema</h3><p>Claro, Oscuro y Automático siguen en el selector del encabezado.</p></section>
    </div>
    <div class="siget-customizer-foot"><button type="button" class="btn btn-outline-secondary w-100" data-zenith-reset><i class="bi bi-arrow-counterclockwise me-1"></i>Restablecer apariencia</button></div>
  </aside>
</div>@stack('scripts')</body></html>
